#!/usr/bin/env python3
#
# Copyright 2026 Genvid Holdings, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Article 50 readiness scan for a local directory of media assets.

Walks a directory, reads what each file actually carries in its own bytes
(content credentials, XMP, IPTC digital source type, generator metadata,
sidecars), reconciles that against an operator-authored declaration, and emits:

  1. a machine-readable disclosure report (JSON), and
  2. a gap list (Markdown) naming every asset whose transparency posture is
     unresolved and what would resolve it.

WHAT THIS TOOL IS NOT
---------------------
It does not decide whether anyone complies with anything. Compliance under
Regulation (EU) 2024/1689 turns on facts this tool cannot see: who the
provider is, who the deployer is, what was actually generated by whom, and how
the content is presented to people. This tool reports evidence and the absence
of evidence. Every conclusion it prints is scoped to "what is present in these
bytes". Read the gap list as a work list, not as a verdict, and route the
result past someone qualified to give legal advice.

It also cannot see imperceptible watermarks. Detecting a watermark requires the
detector that matches the embedder; no metadata read can stand in for that. The
report says so explicitly on every asset rather than scoring the axis silently.

Stdlib only. No network. No account. Python 3.9+.

Usage:
    python3 article50_scan.py PATH [-o OUTDIR] [--json PATH] [--gaps PATH]
                                   [--declaration PATH] [--max-bytes N]

Exit codes:
    0  scan completed, no gaps recorded
    1  scan completed, one or more gaps recorded
    2  the scan could not run (bad path, unreadable declaration)
"""
from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import struct
import sys
from pathlib import Path

TOOL_NAME = "article50_scan"
TOOL_VERSION = "1.0.0"
REPORT_SCHEMA = "genvid.article50-disclosure-report/v1"
DECLARATION_SCHEMA = "genvid.article50-declaration/v1"

# Article 50 of Regulation (EU) 2024/1689 applies from 2 August 2026
# (Article 113). Paragraph references used in this report:
#   50(1) provider  -- systems interacting directly with natural persons are
#                      designed so the person is informed they are dealing with
#                      an AI system, unless that is obvious in context.
#   50(2) provider  -- systems generating synthetic audio/image/video/text mark
#                      their output in a machine-readable format and make it
#                      detectable as artificially generated or manipulated.
#   50(3) deployer  -- emotion recognition / biometric categorisation: inform
#                      the people exposed to it.
#   50(4) deployer  -- FIRST subparagraph: deep fakes are disclosed as
#                      artificially generated or manipulated. Where the content
#                      forms part of an evidently artistic, creative, satirical,
#                      fictional or analogous work, the obligation is LIMITED to
#                      disclosing the existence of such content in a manner that
#                      does not hamper the display or enjoyment of the work --
#                      an attenuation, not an exemption, and the carve-out
#                      reaches deep fakes only.
#                      SECOND subparagraph: AI-generated text published to inform
#                      the public on matters of public interest is disclosed,
#                      unless it underwent human review or editorial control and
#                      someone holds editorial responsibility. The artistic
#                      carve-out does NOT reach this obligation.
#   50(5) both      -- the information above is given at the latest at the
#                      first interaction or exposure, in a clear and
#                      distinguishable manner, conforming to the applicable
#                      accessibility requirements.
#   50(6)           -- without prejudice to the rest of the Regulation.
#   50(7)           -- codes of practice at Union level.
#
# 50(2) and 50(4) are SEPARATE axes. A machine-readable marking never discharges
# 50(4): such markings are not immediately clear and distinguishable to the
# people exposed to the content. This tool keeps the two apart deliberately.
ARTICLE_APPLIES_FROM = "2026-08-02"
# Generative systems placed on the market or put into service before the date
# above have a transitional period to bring the 50(2) marking and detection
# obligations into conformity. It reaches 50(2) only.
ARTICLE_50_2_TRANSITION_ENDS = "2026-12-02"

# ---------------------------------------------------------------------------
# File classification
# ---------------------------------------------------------------------------

IMAGE_EXT = {
    ".jpg", ".jpeg", ".jpe", ".png", ".webp", ".gif", ".tif", ".tiff",
    ".bmp", ".avif", ".heic", ".heif", ".dng", ".exr", ".tga",
}
VIDEO_EXT = {".mp4", ".m4v", ".mov", ".webm", ".mkv", ".avi", ".mxf", ".mpg", ".mpeg"}
AUDIO_EXT = {".wav", ".mp3", ".m4a", ".aac", ".flac", ".ogg", ".oga", ".opus", ".aiff", ".aif"}
TEXT_EXT = {".txt", ".md", ".srt", ".vtt", ".fountain", ".rtf", ".html", ".htm"}

MODALITY_BY_EXT = {}
for _ext in IMAGE_EXT:
    MODALITY_BY_EXT[_ext] = "image"
for _ext in VIDEO_EXT:
    MODALITY_BY_EXT[_ext] = "video"
for _ext in AUDIO_EXT:
    MODALITY_BY_EXT[_ext] = "audio"
for _ext in TEXT_EXT:
    MODALITY_BY_EXT[_ext] = "text"

# Directories that are never assets themselves.
SKIP_DIRS = {".git", ".svn", "__pycache__", "node_modules", ".DS_Store", ".venv", "venv"}

# Sidecar / declaration filenames recognized without being told.
DECLARATION_NAMES = ("article50.json", ".article50.json", "article50-declaration.json")
DISCLOSURE_NAMES = (
    "disclosure.md", "disclosure.txt",
    "ai-disclosure.md", "ai-disclosure.txt",
    "ai_disclosure.md", "ai_disclosure.txt",
)

# ---------------------------------------------------------------------------
# Content-credential markers
# ---------------------------------------------------------------------------
#
# C2PA content credentials are carried differently per container. The markers
# below are the concrete byte-level anchors a reader can find without pulling in
# a C2PA library. Detecting the anchor proves a manifest is PRESENT; it does not
# validate the manifest's signature, and this tool says so.

# Top-level BMFF (MP4/MOV/HEIC/AVIF) 'uuid' box carrying a C2PA manifest store.
# Written as unhyphenated hex on purpose -- the pack's publish gate rejects any
# hyphenated UUID string in published files as a tenant identifier.
C2PA_BMFF_UUID = bytes.fromhex("d8fec3d61b0e483c92975828877ec481")
# The JUMBF superbox type UUID for a C2PA manifest store, whose first four bytes
# are the ASCII "c2pa". This is the one marker common to EVERY container, so it
# is the most reliable single anchor across formats this reader does not walk
# box-by-box. Confirmed against C2PA specification 2.4 and the c2pa-rs reader.
C2PA_JUMBF_TYPE_UUID = bytes.fromhex("6332706100110010800000aa00389b71")
PNG_C2PA_CHUNK = b"caBX"
WEBP_C2PA_CHUNK = b"C2PA"
JUMBF_C2PA_LABEL = b"c2pa"
C2PA_TEXT_MARKERS = (b"c2pa.claim", b"c2pa.assertions", b"c2pa.signature", b"jumdc2pa")
SIDECAR_SUFFIXES = (".c2pa",)

XMP_OPEN = b"<x:xmpmeta"
XMP_CLOSE = b"</x:xmpmeta>"

# IPTC Digital Source Type NewsCodes values, carried in XMP as
# Iptc4xmpExt:DigitalSourceType (namespace http://iptc.org/std/Iptc4xmpExt/
# 2008-02-29/, IPTC Photo Metadata Standard 2025.1 s11.13). Match on the term
# IDENTIFIER, never on its label: the 2024 Q3 release relabelled eight terms
# while keeping their identifiers.
IPTC_SYNTHETIC_TERMS = {
    "trainedalgorithmicmedia": "generated by a model trained on sampled content",
    "compositewithtrainedalgorithmicmedia": "composite including model-generated elements",
    # C2PA's own Implementation Guidance carries this misspelling, so it turns
    # up in real manifests. No erratum has been issued; match it rather than
    # miss a marked asset over a typo upstream.
    "compositedwithtrainedalgorithmicmedia": "composite including model-generated elements",
    "algorithmicmedia": "generated purely by an algorithm",
    "algorithmicallyenhanced": "algorithmically enhanced capture",
    "compositesynthetic": "composite including synthetic elements",
    "virtualrecording": "recording of a virtual scene",
}
# Terms asserting an origin that is NOT model-generated. This bucket covers both
# camera captures and software-authored work, because the only distinction
# Article 50 turns on is whether a model generated the content.
IPTC_NOT_SYNTHETIC_TERMS = {
    "digitalcapture": "captured with a digital camera",
    "computationalcapture": "computational capture",
    "negativefilm": "digitized from a negative",
    "positivefilm": "digitized from a positive",
    "print": "digitized from a print",
    "humanedits": "captured, with human edits",
    "composite": "composite of captured elements",
    "compositecapture": "composite of captured elements",
    "screencapture": "captured from a screen",
    "digitalcreation": "authored with software, not a model",
    "datadrivenmedia": "rendered from data",
    # Retired identifiers, kept so older files still resolve.
    "minorhumanedits": "captured, with minor human edits (retired term)",
    "softwareimage": "authored with software, not a model (retired term)",
    "digitalart": "authored with software, not a model (retired term)",
}
# The property is serialized several ways in the wild, as element content
# (<Iptc4xmpExt:DigitalSourceType>URI</...>), as a plain attribute value, and as
# an rdf:resource attribute (<... rdf:resource="URI"/>). Rather than guess where
# the value sits relative to the property name, find the property and then look
# for a known term in the window that follows it. Terms are matched longest
# first, so compositeWithTrainedAlgorithmicMedia is not shortened to
# trainedAlgorithmicMedia, and neither is shortened to algorithmicMedia.
DIGITAL_SOURCE_PROPERTY = "digitalsourcetype"
DIGITAL_SOURCE_WINDOW = 400

# Generator fingerprints found in embedded metadata. Presence is a strong hint
# of synthetic origin; absence proves nothing at all.
GENERATOR_SIGNATURES = (
    (b"midjourney", "Midjourney"),
    (b"stable diffusion", "Stable Diffusion"),
    (b"stablediffusion", "Stable Diffusion"),
    (b"automatic1111", "AUTOMATIC1111"),
    (b"comfyui", "ComfyUI"),
    (b"invokeai", "InvokeAI"),
    (b"dall-e", "DALL-E"),
    (b"dalle", "DALL-E"),
    (b"openai", "OpenAI"),
    (b"sora", "Sora"),
    (b"firefly", "Adobe Firefly"),
    (b"adobe firefly", "Adobe Firefly"),
    (b"runway", "Runway"),
    (b"kling", "Kling"),
    (b"veo", "Veo"),
    (b"imagen", "Imagen"),
    (b"gemini", "Gemini"),
    (b"flux", "FLUX"),
    (b"black forest labs", "Black Forest Labs"),
    (b"luma", "Luma"),
    (b"pika", "Pika"),
    (b"higgsfield", "Higgsfield"),
    (b"elevenlabs", "ElevenLabs"),
    (b"suno", "Suno"),
    (b"udio", "Udio"),
    (b"heygen", "HeyGen"),
    (b"synthesia", "Synthesia"),
    (b"topaz", "Topaz"),
    (b"nano banana", "Nano Banana"),
)

# PNG text-chunk keys that generators use to stash prompts and parameters.
GENERATOR_PNG_KEYS = {"parameters", "prompt", "workflow", "sd-metadata", "invokeai_metadata", "comment"}

DEFAULT_MAX_BYTES = 8 * 1024 * 1024  # metadata lives at the head or tail


# ---------------------------------------------------------------------------
# Low-level readers
# ---------------------------------------------------------------------------

def _read_edges(path: Path, max_bytes: int):
    """Return (head, tail, size). Metadata boxes cluster at both ends."""
    size = path.stat().st_size
    with path.open("rb") as fh:
        if size <= max_bytes * 2:
            data = fh.read()
            return data, b"", size
        head = fh.read(max_bytes)
        fh.seek(-max_bytes, os.SEEK_END)
        tail = fh.read(max_bytes)
    return head, tail, size


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _extract_xmp(blob: bytes) -> str:
    """Return every XMP packet in ``blob`` as one decoded string."""
    packets = []
    start = blob.find(XMP_OPEN)
    while start != -1 and len(packets) < 8:
        end = blob.find(XMP_CLOSE, start)
        if end == -1:
            packets.append(blob[start:start + 200000].decode("utf-8", "replace"))
            break
        packets.append(blob[start:end + len(XMP_CLOSE)].decode("utf-8", "replace"))
        start = blob.find(XMP_OPEN, end)
    return "\n".join(packets)


def _png_chunks(blob: bytes):
    """Yield (type, payload) for each PNG chunk. Tolerates truncation."""
    if not blob.startswith(b"\x89PNG\r\n\x1a\n"):
        return
    pos = 8
    limit = len(blob)
    while pos + 8 <= limit:
        (length,) = struct.unpack(">I", blob[pos:pos + 4])
        ctype = blob[pos + 4:pos + 8]
        start = pos + 8
        end = start + length
        if length > limit or end > limit:
            return
        yield ctype, blob[start:end]
        pos = end + 4
        if ctype == b"IEND":
            return


def _bmff_boxes(blob: bytes):
    """Yield (type, payload) for top-level ISO-BMFF boxes. Tolerates truncation."""
    pos = 0
    limit = len(blob)
    while pos + 8 <= limit:
        (size,) = struct.unpack(">I", blob[pos:pos + 4])
        btype = blob[pos + 4:pos + 8]
        header = 8
        if size == 1:
            if pos + 16 > limit:
                return
            (size,) = struct.unpack(">Q", blob[pos + 8:pos + 16])
            header = 16
        elif size == 0:
            size = limit - pos
        if size < header:
            return
        end = pos + size
        yield btype, blob[pos + header:min(end, limit)]
        if end <= pos or end > limit:
            return
        pos = end


def _riff_chunks(blob: bytes):
    """Yield (fourcc, payload) for RIFF (WebP) chunks."""
    if not (blob.startswith(b"RIFF") and blob[8:12] == b"WEBP"):
        return
    pos = 12
    limit = len(blob)
    while pos + 8 <= limit:
        fourcc = blob[pos:pos + 4]
        (length,) = struct.unpack("<I", blob[pos + 4:pos + 8])
        start = pos + 8
        end = start + length
        if end > limit:
            return
        yield fourcc, blob[start:end]
        pos = end + (length & 1)


def _jpeg_segments(blob: bytes):
    """Yield (marker, payload) for JPEG APPn/COM segments."""
    if not blob.startswith(b"\xff\xd8"):
        return
    pos = 2
    limit = len(blob)
    while pos + 4 <= limit:
        if blob[pos] != 0xFF:
            pos += 1
            continue
        marker = blob[pos + 1]
        if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:
            pos += 2
            continue
        if marker == 0xDA:  # start of scan; metadata is behind us
            return
        (length,) = struct.unpack(">H", blob[pos + 2:pos + 4])
        start = pos + 4
        end = pos + 2 + length
        if end > limit or length < 2:
            return
        yield marker, blob[start:end]
        pos = end


def _exif_software(payload: bytes):
    """Pull IFD0 Software (0x0131) / Artist (0x013B) out of an EXIF payload."""
    if payload.startswith(b"Exif\x00\x00"):
        payload = payload[6:]
    if len(payload) < 8:
        return {}
    if payload[:2] == b"II":
        endian = "<"
    elif payload[:2] == b"MM":
        endian = ">"
    else:
        return {}
    try:
        (offset,) = struct.unpack(endian + "I", payload[4:8])
        if offset + 2 > len(payload):
            return {}
        (count,) = struct.unpack(endian + "H", payload[offset:offset + 2])
        found = {}
        for i in range(min(count, 512)):
            entry = offset + 2 + i * 12
            if entry + 12 > len(payload):
                break
            tag, ftype, num = struct.unpack(endian + "HHI", payload[entry:entry + 8])
            if tag not in (0x0131, 0x013B, 0x010E) or ftype != 2:
                continue
            if num <= 4:
                raw = payload[entry + 8:entry + 8 + num]
            else:
                (voff,) = struct.unpack(endian + "I", payload[entry + 8:entry + 12])
                raw = payload[voff:voff + num]
            text = raw.split(b"\x00", 1)[0].decode("utf-8", "replace").strip()
            if text:
                found[{0x0131: "software", 0x013B: "artist", 0x010E: "description"}[tag]] = text
        return found
    except (struct.error, IndexError, KeyError):
        return {}


# ---------------------------------------------------------------------------
# Signal extraction
# ---------------------------------------------------------------------------

def _detect_c2pa(blob: bytes, ext: str):
    """Return (present: bool, how: list[str]). Presence only -- not validity."""
    how = []
    if ext == ".png":
        for ctype, _payload in _png_chunks(blob):
            if ctype == PNG_C2PA_CHUNK:
                how.append("PNG caBX chunk")
                break
    if ext == ".webp":
        for fourcc, _payload in _riff_chunks(blob):
            if fourcc == WEBP_C2PA_CHUNK:
                how.append("WebP C2PA chunk")
                break
    if ext in (".jpg", ".jpeg", ".jpe"):
        for marker, payload in _jpeg_segments(blob):
            if marker == 0xEB and (JUMBF_C2PA_LABEL in payload[:512] or b"jumb" in payload[:64]):
                how.append("JPEG APP11 JUMBF segment")
                break
    if ext in (".mp4", ".m4v", ".mov", ".m4a", ".heic", ".heif", ".avif"):
        for btype, payload in _bmff_boxes(blob):
            if btype == b"uuid" and payload[:16] == C2PA_BMFF_UUID:
                how.append("BMFF top-level uuid box")
                break
    if not how:
        # Fallback for containers this reader does not walk box-by-box, and for
        # files large enough that only their two ends were read (where a box
        # walk cannot stay aligned).
        if C2PA_JUMBF_TYPE_UUID in blob:
            how.append("C2PA JUMBF manifest store present in container")
        elif C2PA_BMFF_UUID in blob:
            how.append("C2PA box identifier present in container")
        else:
            for marker in C2PA_TEXT_MARKERS:
                if marker in blob:
                    how.append("C2PA marker bytes present in container")
                    break
    return bool(how), how


def _detect_sidecars(path: Path):
    """Content credentials or disclosure text parked next to the asset."""
    found = []
    for suffix in SIDECAR_SUFFIXES:
        for candidate in (path.with_suffix(path.suffix + suffix), path.with_suffix(suffix)):
            if candidate.is_file():
                found.append(candidate.name)
    for candidate in (
        path.with_suffix(path.suffix + ".json"),
        path.with_suffix(path.suffix + ".provenance.json"),
    ):
        if candidate.is_file():
            try:
                text = candidate.read_text(encoding="utf-8", errors="replace")[:200000]
            except OSError:
                continue
            if any(key in text for key in ("c2pa", "claim_generator", "digitalSourceType", "provenance")):
                found.append(candidate.name)
    return found


def _detect_iptc(xmp: str):
    """Return (value, classification, phrase) from an XMP digital source type."""
    if not xmp:
        return None, "absent", None
    low = xmp.lower()
    at = low.find(DIGITAL_SOURCE_PROPERTY)
    if at == -1:
        return None, "absent", None
    start = at + len(DIGITAL_SOURCE_PROPERTY)
    window = low[start:start + DIGITAL_SOURCE_WINDOW]

    known = [(t, "synthetic", p) for t, p in IPTC_SYNTHETIC_TERMS.items()]
    known += [(t, "not_synthetic", p) for t, p in IPTC_NOT_SYNTHETIC_TERMS.items()]
    known.sort(key=lambda item: -len(item[0]))
    for term, classification, phrase in known:
        for match in re.finditer(re.escape(term), window):
            before = window[match.start() - 1] if match.start() else ""
            after = window[match.end():match.end() + 1]
            # Require the term to stand alone, so 'print' does not match inside
            # 'printer' and 'composite' does not match inside a longer word.
            if before.isalpha() or after.isalpha():
                continue
            # Slice the original string so the value keeps its real casing.
            original = xmp[start + match.start():start + match.end()]
            return original, classification, phrase

    # The property is there but its value is not a term this tool knows. Report
    # the value rather than the axis as absent -- the file did state something.
    tail = re.search(r"[/:=>\"'\s]([A-Za-z][A-Za-z0-9_-]{2,})\s*[\"'<]", xmp[start:start + DIGITAL_SOURCE_WINDOW])
    return (tail.group(1) if tail else None), "unrecognized", None


def _detect_generator(blob: bytes, xmp: str, ext: str):
    """Return (names, evidence, generation_params) for generator fingerprints.

    Deliberately scoped to metadata regions, never the pixel/sample payload, so
    a photograph of a poster reading 'Midjourney' cannot be mistaken for a
    generated frame.

    ``generation_params`` is True when the file carries a metadata key that only
    a generation pipeline writes (a prompt, a sampler/step block, a node graph).
    That is an origin signal in its own right, independent of whether the model
    named in it is one this tool has heard of.
    """
    regions = []
    evidence = []
    generation_params = False
    if xmp:
        regions.append(xmp.encode("utf-8", "replace"))
    if ext == ".png":
        for ctype, payload in _png_chunks(blob):
            if ctype in (b"tEXt", b"iTXt", b"zTXt"):
                key = payload.split(b"\x00", 1)[0].decode("utf-8", "replace").strip()
                regions.append(payload)
                if key.lower() in GENERATOR_PNG_KEYS:
                    generation_params = True
                    evidence.append("PNG %s chunk '%s'" % (ctype.decode(), key))
    if ext in (".jpg", ".jpeg", ".jpe"):
        for marker, payload in _jpeg_segments(blob):
            if marker in (0xE1, 0xED, 0xEE, 0xFE):  # APP1/APP13/APP14/COM
                regions.append(payload)
                exif = _exif_software(payload)
                for field, value in exif.items():
                    evidence.append("EXIF %s: %s" % (field, value[:120]))
                    regions.append(value.encode("utf-8", "replace"))
    if ext in (".mp4", ".m4v", ".mov"):
        for btype, payload in _bmff_boxes(blob):
            if btype in (b"moov", b"udta", b"meta", b"free", b"uuid"):
                regions.append(payload[:400000])

    haystack = b"\n".join(regions).lower()
    # Model identifiers are written as slugs at least as often as prose
    # ('stable-diffusion-xl-base-1.0'), so match against a separator-flattened
    # copy as well as the raw bytes.
    flattened = re.sub(rb"[-_./]+", b" ", haystack)
    names = []
    for needle, label in GENERATOR_SIGNATURES:
        if (needle in haystack or needle in flattened) and label not in names:
            names.append(label)
    return names, evidence, generation_params


# ---------------------------------------------------------------------------
# Declaration
# ---------------------------------------------------------------------------

def _load_declaration(root: Path, explicit):
    """Load the operator declaration. Returns (data, path, error)."""
    candidates = [Path(explicit)] if explicit else [root / name for name in DECLARATION_NAMES]
    for candidate in candidates:
        if candidate.is_file():
            try:
                return json.loads(candidate.read_text(encoding="utf-8")), candidate, None
            except (OSError, json.JSONDecodeError) as exc:
                return None, candidate, str(exc)
    if explicit:
        return None, Path(explicit), "declaration file not found"
    return None, None, None


def _declared_for(declaration, relpath: str):
    if not declaration:
        return {}
    assets = declaration.get("assets") or {}
    entry = assets.get(relpath)
    if entry is None:
        entry = assets.get("./" + relpath)
    merged = dict(declaration.get("defaults") or {})
    if isinstance(entry, dict):
        merged.update(entry)
    return merged


# ---------------------------------------------------------------------------
# Per-asset assessment
# ---------------------------------------------------------------------------

def assess_asset(path: Path, root: Path, declaration, max_bytes: int):
    relpath = path.relative_to(root).as_posix()
    ext = path.suffix.lower()
    modality = MODALITY_BY_EXT.get(ext, "other")

    head, tail, size = _read_edges(path, max_bytes)
    blob = head + tail
    xmp = _extract_xmp(blob)

    c2pa_present, c2pa_how = _detect_c2pa(blob, ext)
    sidecars = _detect_sidecars(path)
    iptc_value, iptc_class, iptc_phrase = _detect_iptc(xmp)
    generators, generator_evidence, generation_params = _detect_generator(blob, xmp, ext)
    generator_signal = bool(generators or generation_params)

    declared = _declared_for(declaration, relpath)
    declared_ai = declared.get("ai_generated")
    declared_deepfake = bool(declared.get("deep_fake"))
    declared_artistic = bool(declared.get("artistic_work"))
    declared_disclosure = declared.get("disclosure")
    declared_model = declared.get("model")
    declared_human_review = declared.get("human_review")
    declared_watermark = declared.get("watermark")

    machine_readable = bool(c2pa_present or sidecars or iptc_class == "synthetic")
    marking_kinds = list(c2pa_how)
    if sidecars:
        marking_kinds.append("sidecar: " + ", ".join(sidecars))
    if iptc_class == "synthetic":
        marking_kinds.append("IPTC digital source type: %s" % iptc_value)

    # Origin: what the bytes and the declaration together support.
    if declared_ai is True:
        origin, origin_basis = "synthetic_declared", "declared by the operator"
    elif declared_ai is False and (iptc_class == "synthetic" or generator_signal):
        origin, origin_basis = "contested", "declared not AI-generated, but the file's own metadata says otherwise"
    elif declared_ai is False:
        origin, origin_basis = "not_synthetic_declared", "declared by the operator"
    elif iptc_class == "synthetic":
        origin, origin_basis = "synthetic_marked", "the file marks itself: %s" % (iptc_phrase or iptc_value)
    elif generator_signal:
        origin = "synthetic_indicated"
        origin_basis = (
            "generator metadata present (%s)" % ", ".join(generators) if generators
            else "generation parameters present in the file's metadata (%s)" % "; ".join(generator_evidence[:3])
        )
    elif iptc_class == "not_synthetic":
        origin, origin_basis = "not_synthetic_marked", "the file marks itself: %s" % iptc_phrase
    else:
        origin, origin_basis = "undetermined", "no origin signal in the file and no declaration entry"

    synthetic = origin in ("synthetic_declared", "synthetic_marked", "synthetic_indicated", "contested")

    obligations = []
    if synthetic:
        obligations.append({
            "reference": "Article 50(2)",
            "bears_on": "provider of the generating system",
            "requirement": (
                "output marked in a machine-readable format AND detectable as artificially generated or "
                "manipulated: two obligations, not one. Marking without an available means of detection "
                "does not discharge the paragraph."
            ),
        })
    if declared_deepfake:
        obligations.append({
            "reference": "Article 50(4)",
            "bears_on": "deployer",
            "requirement": (
                "disclose that the content is artificially generated or manipulated; where the work is evidently "
                "artistic, creative, satirical, fictional or analogous, the obligation is limited to disclosing "
                "the existence of the generated content in a manner that does not hamper the display or enjoyment "
                "of the work; an attenuation, not an exemption"
            ),
            "note": (
                "This is not discharged by the machine-readable marking under 50(2): such markings are not "
                "immediately clear and distinguishable to the people exposed to the content. Treat the two "
                "paragraphs as separate axes."
            ),
        })
    if synthetic or declared_deepfake:
        obligations.append({
            "reference": "Article 50(5)",
            "bears_on": "provider and deployer",
            "requirement": "information given at the latest at the first interaction or exposure, clear, distinguishable and accessible",
        })

    human_disclosure = bool(declared_disclosure) or bool(
        declaration and (declaration.get("production") or {}).get("disclosure_statement")
    )

    return {
        "path": relpath,
        "bytes": size,
        "sha256": _sha256(path),
        "modality": modality,
        "extension": ext,
        "origin": origin,
        "origin_basis": origin_basis,
        "declared": {
            "present": bool(declared),
            "ai_generated": declared_ai,
            "deep_fake": declared_deepfake,
            "artistic_work": declared_artistic,
            "model": declared_model,
            "human_review": declared_human_review,
            "disclosure": declared_disclosure,
        },
        "signals": {
            "content_credentials": {
                "present": c2pa_present,
                "detected_via": c2pa_how,
                "signature_validated": False,
                "note": "presence only; this tool does not validate the manifest signature or its trust chain",
            },
            "sidecars": sidecars,
            "digital_source_type": {
                "value": iptc_value,
                "classification": iptc_class,
                "meaning": iptc_phrase,
            },
            "generator_metadata": {
                "matches": generators,
                "generation_parameters_present": generation_params,
                "evidence": generator_evidence[:12],
            },
            "xmp_present": bool(xmp),
            "imperceptible_watermark": {
                "assessed": False,
                "note": "not assessed; detecting a watermark requires the detector matching the embedder",
            },
            "scan_coverage": "whole file" if not tail else "first and last %d bytes" % max_bytes,
        },
        "disclosure": {
            "machine_readable_marking": "present" if machine_readable else "absent",
            "machine_readable_marking_kinds": marking_kinds,
            "human_readable_disclosure": "present" if human_disclosure else "absent",
            # The Code of Practice on Transparency of AI-Generated Content
            # (10 June 2026) expects at least two layers of machine-readable
            # marking: digitally signed metadata AND an imperceptible watermark.
            # Everything this tool can read is the metadata layer, so the second
            # layer can only ever be operator-declared here, never confirmed.
            "marking_layers": {
                "metadata_layer": "present" if machine_readable else "absent",
                "watermark_layer": "declared" if declared_watermark else "not_evidenced",
                "watermark_declared_as": declared_watermark,
            },
        },
        "obligations_engaged": obligations,
    }


def find_gaps(asset):
    """Turn one assessed asset into zero or more gap records."""
    gaps = []
    rel = asset["path"]
    origin = asset["origin"]
    marked = asset["disclosure"]["machine_readable_marking"] == "present"

    if origin == "contested":
        gaps.append({
            "id": "declaration-contradicts-metadata",
            "severity": "high",
            "reference": "Article 50(2)",
            "asset": rel,
            "finding": "The declaration records this asset as not AI-generated, but its own metadata indicates a model produced it (%s)." % asset["origin_basis"],
            "remediation": "Resolve which is correct. If the asset is synthetic, correct the declaration; if the metadata is inherited from a template or an earlier version, strip or correct it before delivery.",
        })
    if origin == "undetermined":
        gaps.append({
            "id": "origin-undetermined",
            "severity": "medium",
            "reference": "Article 50(2)",
            "asset": rel,
            "finding": "Nothing in the file states whether it was generated, manipulated or captured, and no declaration entry covers it.",
            "remediation": "Record this asset in the declaration with ai_generated true or false. An obligation cannot be scoped, discharged or ruled out while the origin is unknown.",
        })
    if origin in ("synthetic_declared", "synthetic_marked", "synthetic_indicated", "contested") and not marked:
        gaps.append({
            "id": "machine-readable-marking-absent",
            "severity": "high",
            "reference": "Article 50(2)",
            "asset": rel,
            "finding": "This asset reads as artificially generated or manipulated (%s), but carries no machine-readable marking a downstream reader could detect." % asset["origin_basis"],
            "remediation": "Attach content credentials to the delivered file, or write the IPTC digital source type into its XMP, so the synthetic origin travels with the bytes.",
        })
    if origin == "synthetic_indicated" and not asset["declared"]["present"]:
        gaps.append({
            "id": "synthetic-undeclared",
            "severity": "medium",
            "reference": "Article 50(2)",
            "asset": rel,
            "finding": "Generator metadata indicates a model produced this asset, but the operator has not declared it.",
            "remediation": "Add a declaration entry naming the model and version. Generator metadata is a hint left by a tool, not a record anyone stands behind.",
        })
    if asset["declared"]["deep_fake"] and asset["disclosure"]["human_readable_disclosure"] == "absent":
        gaps.append({
            "id": "deep-fake-disclosure-absent",
            "severity": "high",
            "reference": "Article 50(4)",
            "asset": rel,
            "finding": "This asset is declared a deep fake, but no human-readable disclosure text is recorded for it or for the production.",
            "remediation": "Write the disclosure a person will actually see and record it in the declaration. Where the work is evidently artistic or fictional the duty is narrower, not absent; it still has to be disclosed in a way that does not hamper the work's display.",
        })
    if (origin in ("synthetic_declared", "synthetic_marked", "synthetic_indicated", "contested")
            and marked
            and asset["disclosure"]["marking_layers"]["watermark_layer"] == "not_evidenced"):
        gaps.append({
            "id": "second-marking-layer-unevidenced",
            "severity": "medium",
            "reference": "Article 50(2)",
            "asset": rel,
            "finding": (
                "The metadata marking layer is present, but nothing evidences a second, durable layer. "
                "The Code of Practice on Transparency of AI-Generated Content expects at least two layers of "
                "machine-readable marking, digitally signed metadata and an imperceptible watermark, because "
                "no single technique currently meets the effectiveness, interoperability, robustness and "
                "reliability requirements on its own for content that can be disseminated online."
            ),
            "remediation": (
                "Add an imperceptible watermark at generation, and record it in the declaration's watermark field "
                "so this scan can see that you did. This tool cannot detect watermarks, so it can neither confirm "
                "nor rule one out; it reports only that no evidence of one reached it."
            ),
        })
    if marked and asset["signals"]["content_credentials"]["present"]:
        gaps.append({
            "id": "manifest-not-validated",
            "severity": "low",
            "reference": "Article 50(2)",
            "asset": rel,
            "finding": "Content credentials are present but this tool does not check the signature or who signed it.",
            "remediation": "Validate the manifest with a C2PA verifier and confirm the signer is one you recognize. A manifest signed by an unrecognized issuer is a delivery-QC event downstream.",
        })
    if asset["declared"]["ai_generated"] is True and not asset["declared"].get("model"):
        gaps.append({
            "id": "model-attribution-missing",
            "severity": "low",
            "reference": "Article 50(2)",
            "asset": rel,
            "finding": "Declared as AI-generated with no model or version recorded.",
            "remediation": "Record the model and version. Attribution is what makes the declaration auditable later.",
        })
    return gaps


def production_gaps(declaration, declaration_path, assets, declaration_error=None):
    """Gaps that belong to the directory as a whole, not to one asset."""
    gaps = []
    if declaration_error:
        # A declaration that is present but unreadable must never degrade
        # quietly into "no declaration" -- that would silently reclassify every
        # declared asset as undetermined and understate what the operator knows.
        gaps.append({
            "id": "declaration-unparsable",
            "severity": "high",
            "reference": "Article 50",
            "asset": None,
            "finding": "A declaration file (%s) is present but could not be parsed: %s. It was ignored, so every origin below rests on file metadata alone." % (
                declaration_path.name if declaration_path else "unknown", declaration_error),
            "remediation": "Fix the JSON and re-run. Until it parses, this report understates what the operator already knows about the material.",
        })
        return gaps
    if declaration is None:
        gaps.append({
            "id": "declaration-absent",
            "severity": "medium",
            "reference": "Article 50",
            "asset": None,
            "finding": "No operator declaration was found in this directory, so every origin call below rests on metadata a tool happened to leave behind.",
            "remediation": "Add an article50.json declaring, per asset, whether it is AI-generated and whether it is a deep fake. See the skill's DECLARATION.md.",
        })
        return gaps

    production = declaration.get("production") or {}
    if not production.get("operator"):
        gaps.append({
            "id": "operator-unnamed",
            "severity": "low",
            "reference": "Article 50",
            "asset": None,
            "finding": "The declaration does not name the operator.",
            "remediation": "Name the legal entity in production.operator. Article 50 splits duties between provider and deployer, and the split is unresolvable while the entity is unnamed.",
        })
    if not production.get("role"):
        gaps.append({
            "id": "role-unstated",
            "severity": "medium",
            "reference": "Article 50",
            "asset": None,
            "finding": "The declaration does not state whether the operator acts as provider, deployer, or both for this content.",
            "remediation": "Set production.role. 50(2) binds the provider of the generating system; 50(4) binds the deployer. Which paragraphs apply to you depends on it.",
        })
    if production.get("public_interest_text") and not production.get("editorial_responsibility"):
        gaps.append({
            "id": "public-interest-text-unreviewed",
            "severity": "high",
            "reference": "Article 50(4)",
            "asset": None,
            "finding": "This production is declared to publish AI-generated text informing the public on matters of public interest, with no human editorial review recorded.",
            "remediation": "Record who held editorial responsibility for the published text, or disclose that it is artificially generated.",
        })
    if any(a["declared"]["deep_fake"] for a in assets) and not production.get("disclosure_statement"):
        gaps.append({
            "id": "production-disclosure-statement-absent",
            "severity": "medium",
            "reference": "Article 50(4)",
            "asset": None,
            "finding": "Assets are declared as deep fakes but the production carries no disclosure statement.",
            "remediation": "Write production.disclosure_statement: the wording a viewer will actually be shown, at the latest at first exposure.",
        })
    return gaps


# ---------------------------------------------------------------------------
# Walk + report
# ---------------------------------------------------------------------------

def walk_assets(root: Path, include_other: bool):
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS and not d.startswith("."))
        for name in sorted(filenames):
            if name.startswith("."):
                continue
            path = Path(dirpath) / name
            ext = path.suffix.lower()
            if ext in MODALITY_BY_EXT:
                yield path
            elif include_other and path.is_file():
                yield path


class ScanError(Exception):
    """The scan could not run at all (as opposed to running and finding gaps)."""


def scan(root: Path, declaration_path=None, max_bytes=DEFAULT_MAX_BYTES, include_other=False):
    declaration, decl_path, decl_error = _load_declaration(root, declaration_path)
    if decl_error and declaration_path:
        # Explicitly named by the operator: refusing is right, because silently
        # scanning without it would answer a different question than the one asked.
        raise ScanError("cannot read declaration %s: %s" % (decl_path, decl_error))

    assets = []
    unreadable = []
    for path in walk_assets(root, include_other):
        if decl_path and path == decl_path:
            continue
        try:
            assets.append(assess_asset(path, root, declaration, max_bytes))
        except (OSError, struct.error) as exc:
            unreadable.append({"path": path.relative_to(root).as_posix(), "error": str(exc)})

    gaps = production_gaps(declaration, decl_path, assets, decl_error)
    for asset in assets:
        gaps.extend(find_gaps(asset))

    disclosure_files = sorted(
        p.name for p in root.iterdir()
        if p.is_file() and p.name.lower() in DISCLOSURE_NAMES
    ) if root.is_dir() else []

    counts = {
        "assets_scanned": len(assets),
        "unreadable": len(unreadable),
        "synthetic_or_indicated": sum(1 for a in assets if a["origin"].startswith("synthetic") or a["origin"] == "contested"),
        "origin_undetermined": sum(1 for a in assets if a["origin"] == "undetermined"),
        "machine_readable_marking_present": sum(1 for a in assets if a["disclosure"]["machine_readable_marking"] == "present"),
        "gaps": len(gaps),
        "gaps_by_severity": {
            level: sum(1 for g in gaps if g["severity"] == level) for level in ("high", "medium", "low")
        },
    }

    return {
        "schema": REPORT_SCHEMA,
        "tool": {"name": TOOL_NAME, "version": TOOL_VERSION, "network_calls": 0, "account_required": False},
        "generated_at": _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "scope": {
            "root": str(root),
            "declaration": decl_path.name if (decl_path and not decl_error) else None,
            "declaration_error": decl_error,
            "disclosure_files": disclosure_files,
            "regulation": "Regulation (EU) 2024/1689, Article 50",
            "applies_from": ARTICLE_APPLIES_FROM,
            "article_50_2_transition_ends": ARTICLE_50_2_TRANSITION_ENDS,
        },
        "limits": [
            "This tool reports evidence found in the files themselves. It does not determine compliance and its output is not legal advice.",
            "Imperceptible watermarks are not assessed. Metadata inspection cannot substitute for the detector that matches the embedder, so a second marking layer can be declared here but never confirmed.",
            "Content-credential detection is presence-only: signatures and trust chains are not validated.",
            "Origin calls for assets with no declaration entry rest on metadata a generating tool happened to leave behind, which any transcode, screenshot or re-encode removes.",
            "Article 50(2) and Article 50(4) are separate axes. A machine-readable marking does not discharge the deep-fake disclosure duty, because such markings are not clear and distinguishable to the people exposed to the content.",
            "Generative systems placed on the market before the application date have a transitional period for the Article 50(2) marking and detection obligations only. Whether that applies to any given system is a question about the system, not about these files.",
            "The formats this tool reads (content credentials, IPTC digital source type) are de-facto industry implementations. Neither is named in the Regulation, the Commission guidelines, or the code of practice, none of which mandates any specific standard.",
        ],
        "counts": counts,
        "assets": assets,
        "unreadable": unreadable,
        "gaps": gaps,
    }


def render_gap_list(report) -> str:
    counts = report["counts"]
    lines = [
        "# Article 50 gap list",
        "",
        "Scope: `%s`" % report["scope"]["root"],
        "Generated: %s by %s %s" % (report["generated_at"], report["tool"]["name"], report["tool"]["version"]),
        "Reference: %s, applies from %s" % (report["scope"]["regulation"], report["scope"]["applies_from"]),
        "",
        "This is a work list built from what the files carry. It is not a compliance",
        "determination and it is not legal advice.",
        "",
        "## Where the directory stands",
        "",
        "| Measure | Count |",
        "| --- | ---: |",
        "| Assets scanned | %d |" % counts["assets_scanned"],
        "| Reading as generated or manipulated | %d |" % counts["synthetic_or_indicated"],
        "| Origin undetermined | %d |" % counts["origin_undetermined"],
        "| Carrying machine-readable marking | %d |" % counts["machine_readable_marking_present"],
        "| Gaps recorded | %d (high %d, medium %d, low %d) |" % (
            counts["gaps"],
            counts["gaps_by_severity"]["high"],
            counts["gaps_by_severity"]["medium"],
            counts["gaps_by_severity"]["low"],
        ),
        "",
    ]

    if not report["gaps"]:
        lines += ["## Gaps", "", "No gaps recorded. That means nothing was found to flag in these bytes,",
                  "not that an obligation has been met.", ""]
    else:
        lines += ["## Gaps", ""]
        for level in ("high", "medium", "low"):
            batch = [g for g in report["gaps"] if g["severity"] == level]
            if not batch:
                continue
            lines += ["### %s (%d)" % (level.capitalize(), len(batch)), ""]
            for gap in batch:
                where = gap["asset"] or "(whole directory)"
                lines += [
                    "- **%s**, `%s`: %s" % (gap["reference"], where, gap["finding"]),
                    "  - id: `%s`" % gap["id"],
                    "  - do: %s" % gap["remediation"],
                ]
            lines.append("")

    lines += ["## What this scan did not check", ""]
    lines += ["- %s" % limit for limit in report["limits"]]
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog=TOOL_NAME,
        description="Scan a local directory of media assets for EU AI Act Article 50 transparency evidence. "
                    "No account, no network, no upload.",
    )
    parser.add_argument("path", help="directory to scan")
    parser.add_argument("-o", "--out", metavar="DIR",
                        help="write article50-disclosure-report.json and article50-gaps.md into DIR")
    parser.add_argument("--json", metavar="PATH", help="write the machine-readable report here ('-' for stdout)")
    parser.add_argument("--gaps", metavar="PATH", help="write the gap list here ('-' for stdout)")
    parser.add_argument("--declaration", metavar="PATH", help="operator declaration (default: article50.json in PATH)")
    parser.add_argument("--include-other", action="store_true",
                        help="also assess files whose extension is not a known media type")
    parser.add_argument("--max-bytes", type=int, default=DEFAULT_MAX_BYTES,
                        help="per-end read budget for large files (default %d)" % DEFAULT_MAX_BYTES)
    parser.add_argument("--exit-zero", action="store_true", help="exit 0 even when gaps are recorded")
    args = parser.parse_args(argv)

    root = Path(args.path).expanduser().resolve()
    if not root.is_dir():
        print("article50_scan: not a directory: %s" % root, file=sys.stderr)
        return 2

    try:
        report = scan(root, args.declaration, args.max_bytes, args.include_other)
    except ScanError as exc:
        print("article50_scan: %s" % exc, file=sys.stderr)
        return 2
    gap_list = render_gap_list(report)
    report_json = json.dumps(report, indent=2, sort_keys=False) + "\n"

    wrote = []
    if args.out:
        outdir = Path(args.out).expanduser().resolve()
        outdir.mkdir(parents=True, exist_ok=True)
        (outdir / "article50-disclosure-report.json").write_text(report_json, encoding="utf-8")
        (outdir / "article50-gaps.md").write_text(gap_list, encoding="utf-8")
        wrote += [str(outdir / "article50-disclosure-report.json"), str(outdir / "article50-gaps.md")]
    if args.json:
        if args.json == "-":
            sys.stdout.write(report_json)
        else:
            Path(args.json).expanduser().write_text(report_json, encoding="utf-8")
            wrote.append(args.json)
    if args.gaps:
        if args.gaps == "-":
            sys.stdout.write(gap_list)
        else:
            Path(args.gaps).expanduser().write_text(gap_list, encoding="utf-8")
            wrote.append(args.gaps)

    if not (args.out or args.json or args.gaps):
        sys.stdout.write(gap_list)
    elif wrote:
        print("article50_scan: wrote %s" % ", ".join(wrote), file=sys.stderr)

    if report["counts"]["gaps"] and not args.exit_zero:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
