"""Stage 5 (runner): clip transfer -> KeyframeSequence -> bind.

Per logical clip (`clipsources.CATALOG`): `transfer()` runs `blender/poses.py`
on the chosen candidate to produce a poses JSON in the target rig's own
world-space rest frame; `build()` writes the KeyframeSequence `.rbxmx` the
title's Rojo project syncs into Studio; `impact()` and `speed_scale()` compute the two
game-facing numbers (`attackImpactDelaySecs`, `animSpeedScale`) the interface
contract hands to the game's own character-type table; `build_kfs()` emits the
Studio step that verifies the synced sequence against what `build()` recorded,
and `publish_clip()` the one that publishes it with
`AssetService:CreateAssetAsync`, so no Save to Roblox click is on the path to a
playable clip; `bind()` writes the
platform-tier registration payloads once a clip has a published Roblox asset
id, and `registered()` records the finalized Genvid media id once the
orchestrator has actually run them.

A clip the archive and the rig do not provide is generated by the caller, with a
text-to-motion model of its own choosing, through the emit/ingest seam
(request.py): `emit_motion()` writes the request, `ingest_motion()` records the
caller's file and binds it as its own model row (render type T2MOTION), and
`transfer(..., source="generated")` reads it back. The runner calls no provider.

ORCHESTRATOR STEPS (written and unit-testable, never executed by this runner):
`bind()` writes `register_media` / `finalize_media_registration` MCP payloads
(platform tier) for the orchestrator to run for real -- a published clip is
platform-custodied media (the bytes live only as a Roblox asset id), and the
boundary rejects a direct `genvid import-generated-media` upload of the
`.rbxmx` outright (422 "Cannot determine media type from filename ...rbxmx",
witnessed 2026-09-04), so there is no synchronous upload call on this path at
all; `registered()` is the second half, run once the orchestrator has the
finalized Genvid media id back.
"""
import argparse
import json
import os
import shutil
import subprocess
from pathlib import Path

import budget
import clipsources
import genvid_bind
import kfs
import manifest
import mesh
import request
import studio
import timing
from impact import impact_time

POSES_SCRIPT = Path(__file__).parent / "blender" / "poses.py"

ANIMS_DIR_ENV = "GAME_ANIMS_DIR"


def anims_dir():
    """Where `build()` writes a clip's KeyframeSequence .rbxmx -- the title's own
    Rojo-synced animation directory, named by $GAME_ANIMS_DIR.

    REQUIRED, with no default. The default this replaced pointed at one checkout
    under the author's home directory: on any other machine it silently wrote a real
    .rbxmx into a path nothing syncs, and reaching Studio is the whole purpose of this
    fallback path. A per-title skill exports the variable (it knows its own repo); a
    caller driving this pack directly passes `--anims-dir`."""
    root = os.environ.get(ANIMS_DIR_ENV)
    if not root:
        raise RuntimeError(
            "%s is not set and has no default: it must name the directory this title's "
            "Rojo project maps its animations from, because a KeyframeSequence written "
            "anywhere else never reaches Studio. Export it (a per-title skill does this "
            "for you) or pass --anims-dir." % ANIMS_DIR_ENV)
    return Path(root).expanduser()


def _resolve_anims_dir(value):
    """An explicit directory, else the required environment variable. Separate from
    `anims_dir()` only because `build`'s own parameter shadows that name."""
    return Path(value).expanduser() if value else anims_dir()


# The generated-motion step (emit/ingest).
MOTION_STEP = "motion"
MOTION_MODEL_TYPE = "text-to-motion"
MOTION_RENDER_TYPE = "T2MOTION"
MOTION_KINDS = ("glb", "fbx")
MOTION_EXT = {"glb": ".glb", "fbx": ".fbx"}
MOTION_DIR = Path("clips") / "motion"
# The skeleton convention a motion file is authored on, as `blender/poses.py`
# reads it: its flag, or None for a skeleton already named for R15.
MOTION_MODES = {"rename": "--rename", "mixamo": "--mixamo", "ual": "--ual", "r15": None}
MOTION_TARGET = {"format": list(MOTION_KINDS), "preferred": "glb",
                 "notes": "One animation clip on this rig's skeleton (or a Mixamo-convention, Rigify DEF- or "
                          "R15-named skeleton), GLB or binary FBX (7.1 or later)."}
MOTION_MUST_SATISFY = [
    "authored on this rig's skeleton, or on a skeleton convention the transfer reads: the rig's own bone "
    "names, Mixamo-convention names, Rigify DEF- names, or R15 names",
    "in place: the root does not travel, for a looping movement clip",
    "the frame rate stated in --params (for example {\"fps\": 30})",
]
MOTION_CHECKED_AT_INGEST = [
    "clip type by content: GLB or binary FBX (7.1 or later)",
    "--mode names the skeleton convention: " + ", ".join(sorted(MOTION_MODES)),
    "a request was emitted (the budget check ran), unless --unrequested",
]


# Where a transferred item's spend is held (`items[<clip>].cost_source`): the
# rig's record for a clip bundled with the rig, nowhere for an archive clip,
# and the motion's own record for a generated one.
COST_SOURCE_RIG = "rig"
COST_SOURCE_NONE = "none"
NO_CLIP_FILES = ("stages.rig has no clip_files: this rig's bundled clips came from the old generator, which "
                 "named them by vendor id. Record each one with `rig ingest model --unrequested \"<reason>\" "
                 "--rig <the raw rig> --clip <Clip>=<file> ...` (adding --supersede when the rig is bound), or "
                 "transfer an archive candidate instead.")


def _rig_clip_path(m, label):
    """A rig-bundled clip's file, from `stages.rig.clip_files` (the rig ingest's
    record) only."""
    files = (m["stages"].get("rig") or {}).get("clip_files")
    if not files:
        raise ValueError(NO_CLIP_FILES)
    if label not in files:
        raise FileNotFoundError("no bundled clip %r on stages.rig.clip_files (have %s): pass --clip %s=<file> "
                                "at `rig ingest model`, or transfer another candidate"
                                % (label, ", ".join(sorted(files)), label))
    return Path(files[label])


def generated_candidate(m, clip):
    """The transfer candidate for `clip`'s generated motion, from its ingest
    record: the recorded file, its skeleton convention, and the catalog's loop
    and priority for the clip."""
    rec = ((m["stages"].get("clips") or {}).get("generated") or {}).get(clip)
    if not rec:
        raise ValueError("no generated motion recorded for %s: run `clips ingest motion --clip %s` first"
                         % (clip, clip))
    base = clipsources.CATALOG[clip][0]
    return {"source": "generated", "ref": rec["artifact"], "mode": MOTION_MODES[rec["mode"]],
            "mode_name": rec["mode"], "loop": base["loop"], "priority": base["priority"]}


ROOT_REFS = ("first", "bind")
# What `impact()` records on stages.clips, all of it for one clip (attackImpactClip).
IMPACT_KEYS = ("attackImpactDelaySecs", "attackImpactRawSecs", "attackImpactClip")


def parse_trim(value):
    """`START:END` seconds of the source clip -> (start, end), refusing anything
    that is not 0 <= START < END. Whether END is inside the clip only Blender
    knows; poses.py refuses that."""
    try:
        start, end = (float(v) for v in str(value).split(":"))
    except ValueError:
        raise ValueError("--trim %r: expected START:END in seconds of the source clip, e.g. 0.4:1.9" % (value,))
    if not 0.0 <= start < end:
        raise ValueError("--trim %r: need 0 <= START < END" % (value,))
    return start, end


def recorded_g(m, clip):
    """The axis map `clip`'s transfer used, read from its poses doc: what
    `--g-from <clip>` forces on another clip of the same skeleton."""
    item = ((m["stages"].get("clips") or {}).get("items") or {}).get(clip)
    path = Path(item["poses"]) if item and item.get("poses") else Path(m["out_dir"]) / "clips" / ("%s.poses.json" % clip)
    if not path.is_file():
        raise ValueError("--g-from %s: no poses doc for %s at %s; transfer %s first" % (clip, clip, path, clip))
    g = json.loads(path.read_text()).get("g")
    if not g:
        raise ValueError("--g-from %s: %s records no axis map (g); re-transfer %s with this pack" % (clip, path, clip))
    return g


def transfer(m, clip, candidate, *, rest="rest.json", archive_root=None, downloads=None, blender=None,
             g=None, g_from=None, no_root=False, root_ref=None, trim=None):
    """Run `blender/poses.py` on `candidate` for `clip`; record the result under
    `stages.clips.items[<clip>]` and return the poses JSON path. A generated
    motion's candidate comes from `generated_candidate()`.

    Transfer options, each passed to poses.py and recorded on the item:
    `g` forces the axis map (`--g=`), and `g_from` forces the one another clip's
    transfer recorded (transfer the walk first: the empirical pick misfires on
    clips that are not walks); `no_root` emits the rotation-only doc;
    `root_ref` measures root motion from the clip's `first` frame (poses.py's
    default) or the `bind` pose; `trim` ("START:END", seconds of the source
    clip) keeps that range only, re-based to start at 0, so `clip_seconds` and
    `scaled_seconds` are the trimmed length."""
    manifest.require_stage(m, "clips")
    if g and g_from:
        raise ValueError("pass --g or --g-from, not both")
    if root_ref is not None and root_ref not in ROOT_REFS:
        raise ValueError("--root-ref must be one of %s" % ", ".join(ROOT_REFS))
    trim_range = parse_trim(trim) if trim is not None else None
    if g_from:
        g = recorded_g(m, g_from)
    source = candidate["source"]
    mode = candidate.get("mode")

    out = Path(m["out_dir"])
    rest_path = Path(rest) if Path(rest).is_absolute() else out / rest
    if source == "generated":
        clip_path = Path(candidate["ref"])
        if not clip_path.is_file():
            raise FileNotFoundError("generated motion for %s not found at %s" % (clip, clip_path))
        cost_source = "clips.generated.%s" % clip
    elif source == "rig-bundled":
        label = str(candidate["ref"])
        clip_path = _rig_clip_path(m, label)
        if not clip_path.is_file():
            raise FileNotFoundError("bundled clip %s is recorded at %s, which is not on disk" % (label, clip_path))
        rig_st = m["stages"].get("rig") or {}
        bound_sha = (rig_st.get("clip_sha256") or {}).get(label)
        if bound_sha and request.sha256_of(clip_path) != bound_sha:
            raise ValueError("bundled clip %s on disk is not the bytes bound as media %s: re-run `rig bind "
                             "--supersede` to bind it, or restore the bound file"
                             % (label, (rig_st.get("clip_media_ids") or {}).get(label)))
        cost_source = COST_SOURCE_RIG
    elif source in ("mixamo-archive", "quaternius"):
        root = Path(archive_root) if archive_root else clipsources.archive_root()
        dl = Path(downloads) if downloads else clipsources.DEFAULT_DOWNLOADS
        clip_path = clipsources.locate(candidate, root, dl)
        if clip_path is None:
            raise FileNotFoundError("no local file found for %s candidate %r (clip %s)" % (source, candidate, clip))
        cost_source = COST_SOURCE_NONE
    else:
        raise ValueError("transfer() cannot resolve source %r for clip %s" % (source, clip))

    # eval_cmd.py's Ctx (its own docstring, "Conventions this module assumes")
    # reads `<out_dir>/clips/<Clip>.poses.json` plus a sibling
    # `<Clip>.traj.json` -- write there, not `<out_dir>/poses/<Clip>.json`,
    # so the E15/E16/E17/E18/E21 gate rows have evidence on disk instead of
    # reading None and failing "missing" forever.
    out_path = out / "clips" / ("%s.poses.json" % clip)
    out_path.parent.mkdir(parents=True, exist_ok=True)  # poses.py itself does not create it
    argv = [blender or shutil.which("blender"), "--background", "--python-exit-code", "1",
            "--python", str(POSES_SCRIPT), "--", str(clip_path), str(rest_path), str(out_path)]
    if mode:
        argv.append(mode)
    argv.append("--rig-height=%s" % m["height_studs"])
    if source == "quaternius":
        argv.append("--action=%s" % candidate["ref"])
    if g:
        argv.append("--g=%s" % g)
    if no_root:
        argv.append("--no-root")
    if root_ref:
        argv.append("--root-ref=%s" % root_ref)
    if trim_range:
        argv.append("--trim=%s:%s" % trim_range)
    r = subprocess.run(argv, capture_output=True, text=True)
    # --python-exit-code 1 (as rig.r15() uses): without it Blender exits 0 on a
    # raised exception too, and a stale poses.json from an earlier run would
    # then read as a successful transfer.
    if r.returncode != 0 or not out_path.exists():
        raise RuntimeError("clip transfer failed for %s (rc=%s, wrote=%s): %s"
                           % (clip, r.returncode, out_path.exists(), r.stderr[-2000:]))
    poses = json.loads(out_path.read_text())
    clip_seconds = poses["clip_seconds"]
    scaled_seconds = timing.scale_time(clip_seconds, m["height_studs"])

    # Ctx.clip_traj reads the world-space trajectories as their own file, a
    # plain {bone: [[t, x, y, z], ...]} -- the same shape metrics.foot_lift /
    # metrics.impact_height take -- not nested under the poses doc's "traj"
    # key. poses.py writes both into the one combined doc; split the
    # trajectories back out to the sibling file Ctx and the eval rows expect.
    traj_path = out / "clips" / ("%s.traj.json" % clip)
    traj_path.write_text(json.dumps(poses["traj"]))

    items = dict(m["stages"].get("clips", {}).get("items") or {})
    st = m["stages"].setdefault("clips", {})
    if st.get("attackImpactClip") == clip:
        # the impact was measured on the clip this transfer replaces: drop it,
        # so `clips impact` re-runs rather than a build re-deriving from it
        for key in IMPACT_KEYS:
            st.pop(key, None)
        manifest.note(m, "clips transfer: %s re-transferred, attackImpact* dropped; re-run `clips impact --clip %s`"
                      % (clip, clip))
    item = {"clip": clip, "source": source, "ref": candidate["ref"], "mode": candidate.get("mode_name", mode),
            "poses": str(out_path), "clip_seconds": clip_seconds, "scaled_seconds": scaled_seconds,
            "loop": candidate["loop"], "priority": candidate["priority"], "cost_source": cost_source,
            # what poses.py reports it did, beside what was asked of it
            "g": poses.get("g"), "g_forced": bool(poses.get("g_forced")), "g_from": g_from,
            "root_motion": poses.get("root_motion", not no_root), "root_ref": poses.get("root_ref", root_ref),
            "trim": list(trim_range) if trim_range else None}
    items[clip] = item
    manifest.set_stage(m, "clips", items=items)
    manifest.save(m)
    return out_path


def clip_title(m, clip, version=1, name=None):
    """The published KeyframeSequence title for this clip.

    `name` overrides the character prefix. It exists because the Studio template
    name and the published clip title are governed by different rules and came
    apart on the bake-off (witnessed 2026-09-04): the cross-track contract pinned
    template names carrying vendor words, and `kfs.clip_name` refuses to build a
    published title from one, since a published asset title carries no source
    brand. Default is the manifest's own `name`, which is already the brand-free
    one (`contract_name` is what the template answers to)."""
    return kfs.clip_name(name or m["name"], clip, version)


# `clips build-kfs --port` served <out_dir> to a Studio step that fetched the
# poses over HttpService. Studio 0.739 took Network away from execute_luau, so
# the flag is refused with the route that replaced it.
PORT_RETIRED = ("clips build-kfs no longer takes --port: it starts no server, since execute_luau has no Network "
                "capability since Studio 0.739. Build the clip with `clips build --clip <Clip> --anims-dir <the "
                "Rojo-mapped animations directory>`, let Rojo sync it into ServerStorage.Assets.Anims, then run "
                "`clips build-kfs` (without --port) to emit the step that verifies it.")


def _built_name(m, clip, step, version=None, name=None):
    """The title `build()` recorded for `clip`, which every later step uses.
    `version`/`name`, when passed, must produce that same title; a mismatch is
    refused rather than acting on a sequence nobody built."""
    items = (m["stages"].get("clips") or {}).get("items") or {}
    if clip not in items:
        raise ValueError("clips.%s(%s): not on stages.clips.items (have %s) -- run clips transfer first"
                         % (step, clip, sorted(items) or "none"))
    item = items[clip]
    built = item.get("kfs_name")
    if not built or not item.get("kfs_expected"):
        raise ValueError(_not_built(clip))
    if version is not None or name is not None:
        title = clip_title(m, clip, version or 1, name)
        if title != built:
            raise ValueError("clips.%s(%s): --version/--name give %s, but `clips build` last wrote %s; "
                             "re-run `clips build` with the same --version/--name, or drop them here"
                             % (step, clip, title, built))
    return item, built


def _not_built(clip):
    return ("clip %s has no `clips build` record (kfs_name, kfs_expected): build it with `clips build --clip %s "
            "--anims-dir <the Rojo-mapped animations directory>` and let Rojo sync it into "
            "ServerStorage.Assets.Anims before `clips build-kfs`" % (clip, clip))


def build_kfs(m, clip, *, version=None, name=None):
    """Emit the `build_kfs` Studio step for `clip`: a READ-ONLY check that the
    KeyframeSequence `build()` wrote has reached ServerStorage/Assets/Anims
    through Rojo, reporting its keyframe count, last keyframe time, loop,
    priority and root pose shape beside the template's root-node bone and
    scale. `studio ingest build_kfs --clip <Clip>` compares that with the
    `kfs_expected` record `build()` left on the clip item and refuses a
    missing sequence or any mismatch.

    The step builds nothing and needs no Network: `execute_luau` runs without
    that capability since Studio 0.739, which is what retired building the
    sequence in Studio from poses served over local HTTP.

    The sequence name is the one `build()` recorded (`_built_name`)."""
    _item, built = _built_name(m, clip, "build_kfs", version, name)
    return studio.emit(m, "build_kfs", CLIP=clip, CLIP_NAME=built)


def publish_clip(m, clip, *, version=None, name=None):
    """Emit the `publish_clip` Studio step: AssetService:CreateAssetAsync on the
    KeyframeSequence `build()` wrote and `build_kfs` verified, which returns a real asset id from the bridge's Edit
    context (witnessed 2026-09-04) and writes it onto the template as
    `<Clip>AnimId`. This is what replaces the manual Save to Roblox click -- and
    it is not optional: an unpublished sequence loads with the right Length and
    never advances.

    Publishes the title `build()` recorded, and only once `studio ingest
    build_kfs` has verified that same title in Studio: publishing is the one
    step that cannot be taken back."""
    _item, title = _built_name(m, clip, "publish_clip", version, name)
    # studio.emit refuses a title build_kfs has not verified (studio.require_verified)
    return studio.emit(m, "publish_clip", CLIP=clip, CLIP_NAME=title,
                       DESCRIPTION="%s clip for %s, built from the transferred poses"
                                   % (clip, manifest.template_name(m)))


def bench(m, clip, *, speed=None, max_wait=25, at=(0, 300, 0)):
    """Emit the `bench_clip` Studio step (PLAY, Server datamodel) for a clip that
    has ALREADY been published: the clone plays the published id, since a parked
    sequence never advances. `speed` defaults to 1 (a death/attack clip) --
    pass `m["stages"]["clips"]["animSpeedScale"]` for a walk, or the sqrt-height
    ratio when a rig borrows another rig's clip (SKILL.md law 6)."""
    items = (m["stages"].get("clips") or {}).get("items") or {}
    if clip not in items:
        raise ValueError("clips.bench(%s): not on stages.clips.items (have %s) -- run clips transfer first"
                         % (clip, sorted(items) or "none"))
    item = items[clip]
    roblox_id = item.get("roblox_id")
    if not roblox_id:
        raise ValueError("clips.bench(%s): no roblox_id on the clip item -- publish it first "
                         "(clips publish-clip + studio ingest publish_clip --clip %s)" % (clip, clip))
    return studio.emit(m, "bench_clip", CLIP=clip, ANIM_ID="rbxassetid://%s" % roblox_id,
                       SPEED=float(speed or 1), MAX_WAIT=int(max_wait),
                       BENCH_X=at[0], BENCH_Y=at[1], BENCH_Z=at[2])


def build(m, clip, *, anims_dir=None, version=1, name=None, time_scale=None):
    """Write the clip's KeyframeSequence .rbxmx (name via `clip_title`) into
    `anims_dir` -- the title's own Rojo-mapped animation directory, defaulting to
    $GAME_ANIMS_DIR, which is required (see `anims_dir()`) -- and record it on the
    clip's item and on `stages.clips.clip_names` (E22's naming-law gate reads
    this list).

    This is how a clip reaches Studio: Rojo syncs the file into
    ServerStorage/Assets/Anims, `build_kfs` verifies it there against
    `kfs_expected` (recorded here), and `publish_clip` publishes it. No Studio
    step fetches anything, because `execute_luau` has no Network capability
    since Studio 0.739.

    `time_scale` multiplies the authored keyframe times; None (the default) is
    the sqrt-cadence stretch for this character's height (`timing.scale_time`,
    law 6), and 1 keeps a clip authored on this rig at its own cadence. The
    effective factor is recorded in `kfs_expected.time_scale`.

    Rewriting the file drops any earlier `kfs_verified`: that read-back was of
    the previous file, and `publish_clip` requires one of this file."""
    if time_scale is not None and not float(time_scale) > 0:
        raise ValueError("clips.build(%s): --time-scale must be positive (got %r)" % (clip, time_scale))
    items = dict(m["stages"]["clips"]["items"])
    item = items[clip]
    st = m["stages"]["clips"]
    raw_impact = st.get("attackImpactRawSecs") if st.get("attackImpactClip") == clip else None
    if raw_impact is not None and float(raw_impact) > float(item["clip_seconds"]) + 1e-6:
        raise ValueError("clips.build(%s): the recorded impact (%.3f s authored) is past the clip's end (%.3f s): it "
                         "was measured on an earlier transfer. Re-run `clips impact --clip %s` first"
                         % (clip, float(raw_impact), float(item["clip_seconds"]), clip))
    poses = json.loads(Path(item["poses"]).read_text())
    name = clip_title(m, clip, version, name)
    path = _resolve_anims_dir(anims_dir) / ("%s.rbxmx" % name)
    wire = (m["stages"].get("wire") or {}).get("result") or {}
    # the Studio scale step's factor (stages.wire.result.scale, from wire.luau's
    # ingest) is what the Animator multiplies pose translations by
    root_scale = float(wire.get("scale") or 1.0)
    # An adopted rig records whether it carries the HumanoidRootNode bone
    # (adopt_inspect); a runner-built R15 rig always does (clip transfer law 3).
    root_node = wire.get("hasRootNode") is not False
    kfs.write(poses, path, name=name, height_studs=m["height_studs"], loop=item["loop"], priority=item["priority"],
              root_scale=root_scale, root_node=root_node, time_scale=time_scale)
    frames = poses["frames"]
    effective = timing.scale_time(1.0, m["height_studs"]) if time_scale is None else float(time_scale)

    def at(t):  # the time kfs.write gives an authored time, by the same expression
        return timing.scale_time(t, m["height_studs"]) if time_scale is None else t * float(time_scale)
    # What build_kfs's Studio read-back must show for this file to be the one
    # Rojo synced. Keyframe times are written to 5 decimals (kfs.write).
    expected = {"keyframes": len(frames),
                "last_time": round(max((at(fr["t"]) for fr in frames), default=0.0), 5), "time_scale": effective,
                "loop": bool(item["loop"]), "priority": item["priority"], "root_node": root_node,
                "root_scale": root_scale, "root_motion": any(fr.get("r") for fr in frames)}
    item = {k: v for k, v in item.items() if k != "kfs_verified"}
    # The item's time_scale is what every derived timing reads (timing.clip_time):
    # None keeps the height stretch, exactly as before any build.
    item.update(rbxmx=str(path), kfs_name=name, kfs_expected=expected,
                time_scale=None if time_scale is None else float(time_scale))
    item["scaled_seconds"] = timing.clip_time(item, item["clip_seconds"], m["height_studs"])
    items[clip] = item
    names = sorted(set((m["stages"]["clips"].get("clip_names") or [])) | {name})
    manifest.set_stage(m, "clips", items=items, clip_names=names)
    st = m["stages"]["clips"]
    if st.get("attackImpactClip") == clip and st.get("attackImpactRawSecs") is not None:
        # impact() ran before this build: re-derive the delay at the new scale
        manifest.set_stage(m, "clips", attackImpactDelaySecs=timing.clip_time(
            item, st["attackImpactRawSecs"], m["height_studs"]))
    manifest.save(m)
    return path


def impact(m, clip):
    """Impact time for `clip` (scaled by timing), recorded as
    `stages.clips.attackImpactDelaySecs`. impact_time()'s 0.0 return means "no
    lift found in this clip's trajectory" (impact.py's own docstring) -- never
    record that as a real delay, since the game would then fire damage on
    frame one; raise instead so the caller picks a different candidate."""
    item = m["stages"]["clips"]["items"][clip]
    poses = json.loads(Path(item["poses"]).read_text())
    t = impact_time(poses["traj"])
    if t <= 0.0:
        raise RuntimeError(
            "impact.impact_time found no lift-then-strike in the %r clip's trajectory (0.0 back); "
            "recording that as attackImpactDelaySecs would fire damage on frame one -- try a "
            "different candidate for this clip" % clip)
    # scaled the way the built clip plays (the item's time_scale, else the
    # height stretch); the raw time is kept so a later `clips build` at another
    # --time-scale re-derives it
    scaled = timing.clip_time(item, t, m["height_studs"])
    manifest.set_stage(m, "clips", attackImpactDelaySecs=scaled, attackImpactRawSecs=t, attackImpactClip=clip)
    manifest.save(m)
    return scaled


def speed_scale(m):
    """animSpeedScale = walkSpeed / strideStudsPerSec, from the in-engine
    treadmill measurement (`studio.py` ingests `treadmill.luau`'s
    `strideStudsPerSec` to `stages.clips.treadmill`) and `m["walk_speed"]` --
    the game-side Humanoid.WalkSpeed for this character type (the game's own
    concern, not a runner stage output; eval_cmd.py's E19 row already reads
    this same top-level manifest convention -- see its `_row_E19` docstring)."""
    treadmill = m["stages"].get("clips", {}).get("treadmill")
    if not treadmill or not treadmill.get("strideStudsPerSec"):
        raise RuntimeError("no stages.clips.treadmill.strideStudsPerSec recorded; "
                           "run `studio emit/ingest treadmill` before speed_scale()")
    walk_speed = m.get("walk_speed")
    if walk_speed is None:
        raise RuntimeError("no walk_speed on the manifest (m['walk_speed']); set the character's "
                           "intended Humanoid.WalkSpeed before computing animSpeedScale")
    scale = float(walk_speed) / float(treadmill["strideStudsPerSec"])
    manifest.set_stage(m, "clips", animSpeedScale=scale)
    manifest.save(m)
    return scale


def _rig_inputs(m):
    """The rig rows a motion is authored on: the R15 FBX row, then its GLB twin
    when the conversion bound one."""
    rig_st = m["stages"].get("rig") or {}
    if not rig_st.get("media_id"):
        raise request.IngestError("no bound rig: a motion is authored on the rig, so bind it first")
    return [("rig", str(rig_st["media_id"]))] + (
        [("rig-glb", str(rig_st["glb_media_id"]))] if rig_st.get("glb_media_id") else [])


def _check_clip(clip):
    if clip not in clipsources.CATALOG:
        raise request.IngestError("unknown clip %r: one of %s" % (clip, ", ".join(sorted(clipsources.CATALOG))))
    return clip


def emit_motion(m, clips, estimate, model=None, no_urls=False, run=subprocess.run):
    """Write one text-to-motion request per clip, behind one budget check for the
    whole set; returns the request paths."""
    manifest.require_stage(m, "clips")
    clips = sorted(dict.fromkeys(_check_clip(c) for c in clips or ()))
    if not clips:
        raise request.IngestError("name at least one --clip")
    roles = _rig_inputs(m)
    entry = budget.gate(m, "clips", estimate, model=model, items=clips)
    ins = request.inputs(m, roles, no_urls=no_urls, run=run)
    paths = []
    for clip in clips:
        cand = clipsources.CATALOG[clip][0]
        ingest = request.ingest_command(m, "clips", MOTION_STEP).replace(
            "--provider", "--clip %s --mode <%s> --provider" % (clip, "|".join(sorted(MOTION_MODES))))
        paths.append(request.write_request(
            m, "clips", MOTION_STEP, clip, model_type=MOTION_MODEL_TYPE, render_type=MOTION_RENDER_TYPE,
            prompt=clipsources.DESCRIPTIONS[clip], inputs=ins, target=MOTION_TARGET,
            must_satisfy=MOTION_MUST_SATISFY, checked_at_ingest=MOTION_CHECKED_AT_INGEST, budget_entry=entry,
            ingest=ingest, extra={"clip": clip, "loop": cand["loop"], "priority": cand["priority"]}))
    return paths


def _check_motion_kind(path):
    """GLB or binary FBX 7.1 or later, worded for a clip."""
    with open(path, "rb") as f:
        head = f.read(64)
    if head.lstrip().startswith(b"; FBX"):
        raise request.IngestError("%s is an ASCII FBX, which Blender cannot import: export the clip as GLB or "
                                  "binary FBX (7.1 or later)" % path)
    request.check_kind(path, MOTION_KINDS)
    return mesh._check_model_kind(path)


def _motion_ids(m):
    return dict((m["stages"].get("clips") or {}).get("motion_media_ids") or {})


def ingest_motion(m, clip, result, att, *, mode, prompt=None, render_type=None, input_media_ids=(),
                  record_only=False, supersede=False, unrequested=None, opener=None, run=subprocess.run):
    """Record the caller's motion for `clip` at `stages.clips.generated.<clip>`
    (the file copied to `<out>/clips/motion/<clip>.<ext>`), then bind it as its
    own model row attesting the caller's provider, model and cost; returns the
    media id (None with `record_only`). `clips transfer --source generated`
    reads it back."""
    manifest.require_stage(m, "clips")
    _check_clip(clip)
    if mode not in MOTION_MODES:
        raise request.IngestError("--mode must be one of %s: the skeleton convention the clip is authored on"
                                  % ", ".join(sorted(MOTION_MODES)))
    if not record_only:
        mesh._bind_preconditions(m)
    req_path = request.require_request(m, "clips", MOTION_STEP, clip, unrequested)
    req = json.loads(Path(req_path).read_text()) if req_path else {}
    ids = [str(i) for i in input_media_ids] or [mid for _role, mid in _rig_inputs(m)]

    def make(path, url, kind):
        rec = request.make_record(
            artifact=path, source_url=url, attestation=att,
            prompt=prompt if prompt is not None else (req.get("prompt") or clipsources.DESCRIPTIONS[clip]),
            render_type=render_type or req.get("render_type") or MOTION_RENDER_TYPE,
            input_media_ids=ids, request_path=req_path, vendor_hint=m.get("vendor"))
        rec.update(kind=kind, mode=mode)
        return rec

    bound = _motion_ids(m).get(clip)
    outcome = request.record_result(m, "clips", clip, result, make, stem=str(MOTION_DIR / clip), ext=MOTION_EXT,
                                    check=_check_motion_kind, bound_media_id=bound, supersede=supersede,
                                    opener=opener)
    rec = m["stages"]["clips"]["generated"][clip]
    dest = Path(m["out_dir"]) / MOTION_DIR / (clip + MOTION_EXT[rec["kind"]])
    if Path(rec["artifact"]).resolve() != dest.resolve():
        # A caller's local file is copied in, so a later transfer still finds it.
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(rec["artifact"], dest)
        rec["artifact"] = str(dest)
    if rec.get("mode") != mode:
        manifest.note(m, "clips ingest motion: %s mode %s -> %s (same bytes)" % (clip, rec.get("mode"), mode))
        rec["mode"] = mode
    manifest.save(m)
    if record_only:
        return None
    if outcome == "unchanged" and bound:
        return bound
    genvid_bind.ensure_claim(m, m["asset_id"], "clips.motion")
    # No target/stage: the platform registration of the published clip carries
    # none either (clips.bind), and the motion file is the clip's source.
    mid = genvid_bind.import_media(
        m["project_id"], link_type=genvid_bind.MODEL_LINK, asset_id=m["asset_id"], run=run,
        **request.bind_kwargs(rec, runner={"stage": "clips", "step": MOTION_STEP, "clip": clip, "mode": mode,
                                           "kind": "animation-clip"}))
    ids_by_clip = _motion_ids(m)
    ids_by_clip[clip] = mid
    manifest.set_stage(m, "clips", motion_media_ids=ids_by_clip)
    manifest.save(m)
    return mid


def _pending_media_id(register_path):
    """Placeholder for `finalize_media_registration`'s required `media_id` field
    (the PENDING registry row id `register_media`'s own response returns) --
    unknowable here, since this runner never calls that MCP tool itself. Names
    the sibling register payload file so the orchestrator knows exactly which
    response to read the real id from before running finalize."""
    return "PENDING:%s" % register_path.name


def _source_citation(m, clip, item):
    """`(input_media_ids, source_record)` for a published clip's registration:
    the Genvid row its motion came from. A generated clip cites its motion row
    and carries that row's attestation; a rig-bundled clip cites its bundled
    clip row (which cites the rig, whose row holds the spend); an archive clip
    cites nothing, since nothing was generated."""
    if item["source"] == "generated":
        motion_id = _motion_ids(m).get(clip)
        if not motion_id:
            raise ValueError("clips.bind(%s): the generated motion is not bound; finish `clips ingest motion "
                             "--clip %s` first" % (clip, clip))
        src = m["stages"]["clips"]["generated"][clip]
        return [str(motion_id)], {
            "model_provider": src["model_provider"], "model_name": src["model_name"],
            "render_type": src["render_type"], "cost": dict(src["cost"]), "media_id": str(motion_id)}
    if item["source"] == "rig-bundled":
        rig_st = m["stages"].get("rig") or {}
        clip_id = (rig_st.get("clip_media_ids") or {}).get(str(item["ref"]))
        if not clip_id:
            raise ValueError("clips.bind(%s): bundled clip %s has no Genvid row on stages.rig.clip_media_ids; "
                             "re-run `rig bind` (or `rig ingest model`) to bind it first" % (clip, item["ref"]))
        return [str(clip_id)], {"cost_source": COST_SOURCE_RIG, "media_id": str(clip_id),
                                "rig_media_id": str(rig_st.get("media_id"))}
    return [], None


def bind(m, ids, version=1, name=None):
    """ORCHESTRATOR STEP for its governed writes -- never called by this
    runner. `ids`: `{clip: roblox_asset_id}` for every clip a human has
    published (`publish_clip`'s `CreateAssetAsync`, or a manual Save to
    Roblox). `version`/`name` match the published title `publish_clip`/
    `build` used (see `clip_title`) -- see the module docstring for why the
    Studio template name and the published title can differ.

    A published clip is PLATFORM-CUSTODIED media: the bytes live only as a
    Roblox asset id, which is exactly what `register_media`'s
    `storage_class="platform"` / `locator_type="platform_asset"` tier is for
    (SKILL.md 5.1) -- and the boundary rejects a direct `genvid
    import-generated-media` upload of a `.rbxmx` outright (422 "Cannot
    determine media type from filename", witnessed 2026-09-04), so there is
    no synchronous upload call on this path at all, unlike `rig.bind()` /
    `mesh.bind()`. Per clip this writes two `register_media` /
    `finalize_media_registration` MCP payloads (`genvid_bind.mcp_payload`,
    for the orchestrator to run for real):

    - `register_media`: `storage_class="platform"`, `kind="animation-clip"`
      (the genvid-media-registration vocabulary for a rig animation, distinct
      from `"mesh"`), `link_type=genvid_bind.MODEL_LINK`
      (`cast_member_model` -- the pack rule is prefix = asset type), a `.glb`
      filename with `mime_type="model/gltf-binary"` (the media-type HINT the
      boundary accepts for a model row; there is no such file -- an `.rbxmx`
      name is rejected outright, so the payload must carry a `.glb` name;
      shape witnessed 2026-09-10). No
      `proxy_filename`: the platform tier permits no proxy.
    - `finalize_media_registration`: `locator="rbxassetid://<id>"`,
      `locator_type="platform_asset"`, `identifiers=[{"identifier_scope":
      "roblox.com", "identifier_value": "asset_id:<id>"}]` (the schema's
      `IdentifierInput` shape, not a bare string list -- `<id>` here is the
      PUBLISHED ROBLOX asset id, never the Genvid anchor id `m["asset_id"]`,
      which is artifact-scoped and, being the same value for every clip,
      would also trip the `(org, scope, value)` duplicate-identifier
      rejection on the second clip's finalize), and `generation={"provider":
      "runner", "model": "world-space-transfer", "prompt": <clip source
      line>, "params": {...}}` (a JSON OBJECT, per the schema, not a
      string). `target="roblox"`/`stage="roblox/keyframesequence"` mirror
      what makes a row conformance-checkable (SKILL.md 5.1); the exact
      `"roblox/keyframesequence"` stage string is UNVERIFIED against a
      published target_vocabulary (the schema says to check one, and no such
      check ran here), carried forward from the code this replaces.
      `input_media_ids=[]`: there is no already-known Genvid media id this
      registration derives from (the old code pointed at its own now-removed
      multipart-import id). Two more schema-required fields are left for the
      orchestrator to fill when it actually runs this: `media_id` (the
      placeholder `_pending_media_id` writes) and `size_bytes` (unknowable
      without reading the .rbxmx this runner never re-opens on this path).

    Records `stages.clips.items[clip].roblox_id` and `.registration =
    {"state": "payload_written", "register_payload": <path>,
    "finalize_payload": <path>}` -- and mirrors the id onto
    `stages.clips.roblox_ids[clip]`, the same shape `publish_clip`'s Studio
    ingest already writes (`studio.ingest(m, "publish_clip", ...)`), so the
    two paths agree. `"payload_written"` is not `"registered"`:
    `manifest.require_stage(m, "record")` (default, strict) will not treat
    this clip as bound until `registered()` below records the orchestrator's
    real finalize result -- or `record run --allow-unregistered` tolerates
    this state and eval row E27 reads PEND, never PASS, for it.
    """
    # Media-bind-only site -- before the first register_media payload, not
    # per-clip (one claim covers every clip's payload pair in this call).
    items = dict(m["stages"]["clips"]["items"])
    # Every clip's source row is resolved before any governed write.
    sources = {clip: _source_citation(m, clip, items[clip]) for clip in ids}
    genvid_bind.ensure_claim(m, m["asset_id"], "clips")
    roblox_ids = dict(m["stages"].get("clips", {}).get("roblox_ids") or {})
    for clip, roblox_id in ids.items():
        item = items[clip]
        title = clip_title(m, clip, version, name)
        # A `.rbxmx` filename is rejected at register_media (422 "Cannot determine
        # media type from filename", 2026-09-04) and so was every bind from
        # 2026-09-04 to 09-09, which the orchestrator re-shaped by hand. The shape
        # that lands (witnessed 2026-09-10 on two bound clips): a geometry
        # extension so the row types as a model, with `kind="animation-clip"`
        # saying what it is. The extension is a media-type hint only -- no file of
        # that name exists; the original is the platform id.
        filename = "%s.glb" % title
        mime_type = "model/gltf-binary"
        # size_bytes is a required finalize field; the published KeyframeSequence
        # has no file, so the size WITNESSED here is the transfer output the
        # sequence was built from, and params says so.
        poses_path = Path(item.get("poses") or "")
        if not poses_path.is_file():
            raise FileNotFoundError("clips.bind(%s): poses file %r not on disk; size_bytes must be measured, not guessed"
                                    % (clip, item.get("poses")))
        size_bytes = poses_path.stat().st_size

        inputs, source_record = sources[clip]
        register_path = genvid_bind.mcp_payload("register_media", m["out_dir"], project_id=m["project_id"],
            link_type=genvid_bind.MODEL_LINK, asset_id=m["asset_id"], filename=filename,
            mime_type=mime_type, storage_class="platform", kind="animation-clip")

        prompt = "%s clip for %s, %s source ref %s (%s world-space transfer)" % (
            clip, manifest.template_name(m), item["source"], item["ref"], item["mode"])
        generation = {"provider": "runner", "model": "world-space-transfer", "prompt": prompt,
                     "params": {"clip": clip, "source": item["source"], "ref": item["ref"], "mode": item["mode"],
                                "clip_seconds": item["clip_seconds"], "scaled_seconds": item["scaled_seconds"],
                                "loop": item["loop"], "priority": item["priority"],
                                "size_bytes_is": "the transfer's poses JSON the KeyframeSequence was built from; "
                                                 "the published sequence has no file"}}
        if source_record:
            generation["params"]["source_record"] = source_record
        identifiers = [{"identifier_scope": "roblox.com", "identifier_value": "asset_id:%s" % roblox_id}]
        finalize_path = genvid_bind.mcp_payload("finalize_media_registration", m["out_dir"],
            project_id=m["project_id"], media_id=_pending_media_id(register_path),
            link_type=genvid_bind.MODEL_LINK, asset_id=m["asset_id"], filename=filename,
            mime_type=mime_type, size_bytes=size_bytes, duration_seconds=item["scaled_seconds"],
            locator="rbxassetid://%s" % roblox_id, locator_type="platform_asset",
            storage_class="platform", identifiers=identifiers, generation=generation, input_media_ids=inputs)
        # No target/stage: finalize rejects target="roblox" + stage="roblox/keyframesequence"
        # ("not a known destination and pipeline stage", 2026-09-08); the clip rows
        # bind without them until the target vocabulary grows a clip stage.

        roblox_ids[clip] = str(roblox_id)
        items[clip] = dict(item, roblox_id=str(roblox_id),
                           registration={"state": "payload_written",
                                        "register_payload": str(register_path),
                                        "finalize_payload": str(finalize_path)})
        manifest.set_stage(m, "clips", items=dict(items), roblox_ids=dict(roblox_ids))
        manifest.note(m, "clips bind: %s registered at platform tier (rbxassetid %s); payloads written "
                          "(%s, %s), awaiting the orchestrator's register_media + finalize_media_registration "
                          "calls and `clips registered --clip %s --media-id <id>`"
                          % (clip, roblox_id, register_path.name, finalize_path.name, clip))
        manifest.save(m)
    return items


def registered(m, clip, media_id):
    """The second half of `bind()`'s platform-tier capture -- run once the
    orchestrator has actually executed `clip`'s `register_media` +
    `finalize_media_registration` payloads and has the finalized Genvid media
    id back. Moves `stages.clips.items[clip].registration.state` from
    `"payload_written"` to `"registered"` and records `media_id` on it; also
    mirrors `media_id` onto `stages.clips.media_ids[clip]` and, for Walk, the
    top-level `stages.clips.media_id` -- the same shapes `record.run()`'s
    per-clip conformance loop and eval row E27's bound-media count already
    read, so neither needed to change to learn about a registration this
    runner itself never makes."""
    items = dict(m["stages"]["clips"]["items"])
    item = items.get(clip)
    if item is None:
        raise ValueError("no stages.clips.items[%r] on the manifest" % clip)
    registration = dict(item.get("registration") or {})
    if not registration:
        raise RuntimeError("clip %r has no registration payloads on record; run `clips bind` for it first" % clip)
    registration.update(state="registered", media_id=media_id)
    items[clip] = dict(item, registration=registration)
    manifest.set_stage(m, "clips", items=items)

    media_ids = dict(m["stages"]["clips"].get("media_ids") or {})
    media_ids[clip] = media_id
    manifest.set_stage(m, "clips", media_ids=media_ids)
    if clip == "Walk":
        manifest.set_stage(m, "clips", media_id=media_id)
    manifest.note(m, "clips registered: %s -> Genvid media %s" % (clip, media_id))
    manifest.save(m)
    return items[clip]


def _transfer_cli(x):
    m = manifest.load(x.manifest)
    if x.source == "generated":
        candidate = generated_candidate(m, x.clip)
    else:
        candidate = clipsources.CATALOG[x.clip][x.candidate]
    transfer(m, x.clip, candidate, rest=x.rest,
             archive_root=x.archive_root, downloads=x.downloads, blender=x.blender,
             g=x.g, g_from=x.g_from, no_root=x.no_root, root_ref=x.root_ref, trim=x.trim)


def _build_cli(x):
    build(manifest.load(x.manifest), x.clip, anims_dir=x.anims_dir, version=x.version, name=x.name,
          time_scale=x.time_scale)


def _build_kfs_cli(x):
    if x.port is not None:
        raise SystemExit(PORT_RETIRED)
    build_kfs(manifest.load(x.manifest), x.clip, version=x.version, name=x.name)
    return 0


def _publish_clip_cli(x):
    publish_clip(manifest.load(x.manifest), x.clip, version=x.version, name=x.name)
    return 0


def _bench_cli(x):
    bench(manifest.load(x.manifest), x.clip, speed=x.speed, max_wait=x.max_wait)
    return 0


def _impact_cli(x):
    impact(manifest.load(x.manifest), x.clip)


def _speed_scale_cli(x):
    speed_scale(manifest.load(x.manifest))


def _no_item(x):
    if x.item:
        raise SystemExit("clips %s %s takes --clip, not --item" % (x.cmd, x.step))


def _emit_motion(x):
    _no_item(x)
    for p in emit_motion(manifest.load(x.manifest), x.clip, x.estimate, model=x.model, no_urls=x.no_urls):
        print(p)


def _ingest_motion(x):
    _no_item(x)
    ingest_motion(manifest.load(x.manifest), x.clip, x.result, request.attestation_from_args(x), mode=x.mode,
                  prompt=x.prompt, render_type=x.render_type, input_media_ids=x.input_media_id,
                  record_only=x.record_only, supersede=x.supersede, unrequested=x.unrequested)


def _bind_cli(x):
    ids = dict(kv.split("=", 1) for kv in x.ids)
    bind(manifest.load(x.manifest), ids, version=x.version, name=x.name)


def _registered_cli(x):
    registered(manifest.load(x.manifest), x.clip, x.media_id)


def register(sub):
    p = sub.add_parser("clips"); s = p.add_subparsers(dest="cmd", required=True)

    a = s.add_parser("transfer"); a.add_argument("--manifest", required=True)
    a.add_argument("--clip", required=True, choices=sorted(clipsources.CATALOG))
    a.add_argument("--candidate", type=int, default=0, help="index into clipsources.CATALOG[clip]")
    a.add_argument("--source", choices=("catalog", "generated"), default="catalog",
                   help="generated: transfer the motion `clips ingest motion` recorded for this clip")
    a.add_argument("--rest", default="rest.json")
    a.add_argument("--archive-root", help="the animation archive tree; defaults to "
                   "$ANIM_LIBRARY_ROOT, which is required when this is omitted")
    a.add_argument("--downloads", help="default: ANIM_LIBRARY_DOWNLOADS env or ~/Downloads")
    a.add_argument("--blender")
    ga = a.add_mutually_exclusive_group()
    ga.add_argument("--g", default=None, help="force the axis map (one of poses.py's 24 candidates, e.g. the "
                    "`g` a walk transfer recorded)")
    ga.add_argument("--g-from", default=None, choices=sorted(clipsources.CATALOG),
                    help="force the axis map another clip's transfer recorded (transfer the walk first)")
    a.add_argument("--no-root", action="store_true", help="rotation-only: emit no root motion")
    a.add_argument("--root-ref", choices=ROOT_REFS, default=None,
                   help="root motion from the clip's first frame (poses.py's default) or the bind pose")
    a.add_argument("--trim", default=None, metavar="START:END",
                   help="keep only this range of the source clip (seconds, authored time), re-based to 0")
    a.set_defaults(func=_transfer_cli)

    b = s.add_parser("build"); b.add_argument("--manifest", required=True)
    b.add_argument("--clip", required=True, choices=sorted(clipsources.CATALOG))
    b.add_argument("--anims-dir", default=None,
                   help="where to write the KeyframeSequence .rbxmx; defaults to "
                        "$GAME_ANIMS_DIR, which is required when this is omitted")
    b.add_argument("--time-scale", type=float, default=None,
                   help="multiply the authored keyframe times by this; default is the sqrt-cadence stretch for "
                        "the character's height, 1 keeps the authored cadence (a clip authored on this rig)")
    b.add_argument("--version", type=int, default=1)
    b.add_argument("--name", default=None,
                   help="character prefix for the published clip title, when the Studio template's "
                        "own name is not one a published asset title may carry (no source brand)")
    b.set_defaults(func=_build_cli)

    bk = s.add_parser("build-kfs", help="emit the Studio step that verifies the KeyframeSequence `clips build` "
                                        "wrote has synced into Studio")
    bk.add_argument("--manifest", required=True)
    bk.add_argument("--clip", required=True, choices=sorted(clipsources.CATALOG))
    bk.add_argument("--version", type=int, default=None,
                    help="optional: must match the title `clips build` recorded")
    bk.add_argument("--name", default=None, help="optional: must match the title `clips build` recorded")
    bk.add_argument("--port", type=int, default=None, help=argparse.SUPPRESS)
    bk.set_defaults(func=_build_kfs_cli)

    pc = s.add_parser("publish-clip", help="emit the Studio step that publishes the built, verified KeyframeSequence")
    pc.add_argument("--manifest", required=True)
    pc.add_argument("--clip", required=True, choices=sorted(clipsources.CATALOG))
    pc.add_argument("--version", type=int, default=None,
                    help="optional: must match the title `clips build` recorded")
    pc.add_argument("--name", default=None, help="optional: must match the title `clips build` recorded")
    pc.set_defaults(func=_publish_clip_cli)

    bc = s.add_parser("bench", help="emit the Play bench step for a PUBLISHED clip (hip drop, slide, head over sole)")
    bc.add_argument("--manifest", required=True)
    bc.add_argument("--clip", required=True, choices=sorted(clipsources.CATALOG))
    bc.add_argument("--speed", type=float, default=None, help="playback speed; default 1")
    bc.add_argument("--max-wait", type=int, default=25, help="seconds the bridge call may block")
    bc.set_defaults(func=_bench_cli)

    c = s.add_parser("impact"); c.add_argument("--manifest", required=True)
    c.add_argument("--clip", required=True, choices=sorted(clipsources.CATALOG))
    c.set_defaults(func=_impact_cli)

    d = s.add_parser("speed-scale"); d.add_argument("--manifest", required=True)
    d.set_defaults(func=_speed_scale_cli)

    em = s.add_parser("emit", help="write the text-to-motion request for the caller's own model")
    ems = em.add_subparsers(dest="step", required=True)
    emm = ems.add_parser("motion", help="one request per clip, behind one budget check")
    request.add_emit_args(emm, item_help="not used: name clips with --clip")
    emm.add_argument("--clip", action="append", required=True, choices=sorted(clipsources.CATALOG),
                     help="a clip to request (repeatable)")
    emm.set_defaults(func=_emit_motion)
    ig = s.add_parser("ingest", help="record the caller's motion, then bind it")
    igs = ig.add_subparsers(dest="step", required=True)
    igm = igs.add_parser("motion", help="one clip's motion file, a local file or a URL")
    request.add_ingest_args(igm, item_help="not used: name the clip with --clip")
    igm.add_argument("--clip", required=True, choices=sorted(clipsources.CATALOG))
    igm.add_argument("--mode", required=True, choices=sorted(MOTION_MODES),
                     help="the skeleton convention the clip is authored on: rename (the rig's own bone names), "
                          "mixamo, ual (Rigify DEF- names) or r15 (already R15-named)")
    igm.set_defaults(func=_ingest_motion)

    f = s.add_parser("bind"); f.add_argument("--manifest", required=True)
    f.add_argument("--ids", required=True, nargs="+", help="Clip=RobloxAssetId pairs, space-separated")
    f.add_argument("--version", type=int, default=1)
    f.add_argument("--name", default=None, help="see `clips build --name`")
    f.set_defaults(func=_bind_cli)

    g = s.add_parser("registered", help="record the finalized Genvid media id for a clip bind() wrote payloads for")
    g.add_argument("--manifest", required=True)
    g.add_argument("--clip", required=True, choices=sorted(clipsources.CATALOG))
    g.add_argument("--media-id", required=True, help="the Genvid media id finalize_media_registration returned")
    g.set_defaults(func=_registered_cli)
