"""Stage 1: the plate. The front concept plate and its back/left/right views, each
generated by the caller with a model of its own choosing and bound under the
asset's image assignment.

    plate emit front   -> request for the front candidates (text-to-image, or
                          image-to-image with --input-media-id references)
    plate ingest front --item c<n> [--create-asset | --asset-id A] <file-or-url>
                       -> records and binds one candidate as cast_member_image
    plate select-front --media-id ID
                       -> records which bound candidate is the front, or adopts a
                          media row already in Genvid as the front
    plate emit views   -> one image-to-image request per view, from the front
    plate ingest views --item back|left|right <file-or-url>
                       -> records and binds one view, citing the front
    plate bind         -> re-runs the bind for every recorded item not yet bound

The runner calls no provider and names no model; every bind attests the
provider, model, params and cost the caller reported at ingest (request.py).
"""
import json, os, re, subprocess
from pathlib import Path
import manifest, genvid_bind, request, budget
# The budget gate lives in budget.py; stages and per-title code still reach it here.
from budget import BudgetError, budget_gate  # noqa: F401

VIEWS = ("back", "left", "right")
VIEW_WORDS = {"back": "seen directly from behind", "left": "seen from its left side in strict profile",
              "right": "seen from its right side in strict profile"}
# The pose and background rules every plate image must meet: the views' prompt
# states them, and both requests list them in must_satisfy.
POSE_AND_BACKGROUND = ("symmetric A-pose with arms angled away from the torso and a clear gap on both sides, legs "
                       "apart, feet shoulder-width, full body head to feet, centered, plain flat neutral gray "
                       "background, even studio lighting, no floor shadow, no text")

def SHEET_PROMPT(view):
    return ("Redraw this exact character %s, same design, colors, materials and proportions, same %s."
            % (VIEW_WORDS[view], POSE_AND_BACKGROUND))

# Budget keys: the front candidates and the views are separate spends.
FRONT_BUDGET = "plate.front"
VIEWS_BUDGET = "plate"
CANDIDATE_RE = re.compile(r"^c[1-9][0-9]*$")
IMAGE_EXT = {"png": ".png", "jpeg": ".jpg", "webp": ".webp"}
CHECKED_AT_INGEST = ["image type by magic bytes: PNG, JPEG or WebP",
                     "a request was emitted for this item (the budget check ran), unless --unrequested"]


def _plate(m):
    return m["stages"].get("plate") or {}


def _media_ids(m):
    return dict(_plate(m).get("media_ids") or {})


def _check_view(view):
    if view not in VIEWS:
        raise ValueError("view %r is not one of %s" % (view, ", ".join(VIEWS)))


def _check_candidate(item):
    if not item or not CANDIDATE_RE.match(str(item)):
        raise ValueError("front candidate %r must be named c1, c2, ... (--item c<n>)" % (item,))


# ---------------------------------------------------------------- emit

def emit_front(m, estimate, prompt=None, input_media_ids=(), model=None, no_urls=False, run=subprocess.run):
    """Write the front request and return its path. The prompt is `prompt` when
    given, else the one a per-title skill recorded at stages.plate.prompt.
    Reference images make it image-to-image. `estimate` covers every candidate
    the caller will generate."""
    manifest.require_stage(m, "plate")
    prompt = prompt or _plate(m).get("prompt")
    if not prompt:
        raise request.IngestError("no front prompt: none is recorded at stages.plate.prompt, so pass --prompt")
    refs = [str(i) for i in input_media_ids]
    entry = budget.gate(m, FRONT_BUDGET, estimate, model=model, items=["front"])
    ins = request.inputs(m, [("reference", i) for i in refs], no_urls=no_urls, run=run)
    return request.write_request(
        m, "plate", "front", None,
        model_type="image-to-image" if refs else "text-to-image", render_type="I2I" if refs else "T2I",
        prompt=prompt, inputs=ins,
        target={"format": ["png"], "orientation": "portrait", "framing": "full body, head to feet"},
        must_satisfy=["the pose and background rules: %s" % POSE_AND_BACKGROUND,
                      "one character per image, portrait"],
        checked_at_ingest=CHECKED_AT_INGEST, budget_entry=entry,
        ingest=request.ingest_command(m, "plate", "front", "c<n>"),
        extra={"candidates": "ingest each candidate you generate as its own item, c1, c2, ...; every "
                             "candidate is bound, then `plate select-front` records the one approved"})


def emit_views(m, estimate, item=None, model=None, no_urls=False, run=subprocess.run):
    """Write one request per view and return their paths. With no `item`, every
    view not yet generated is requested, under one budget verdict; a verdict
    covers its item set, so a later emit for other views gates again."""
    manifest.require_stage(m, "plate")
    if item is not None:
        _check_view(item)
    front = _media_ids(m).get("front")
    if not front:
        raise request.IngestError("no front plate: bind a candidate and run `plate select-front`, or adopt one "
                                  "with `plate select-front --media-id`, before emitting the views")
    generated = _plate(m).get("generated") or {}
    todo = [item] if item else [v for v in VIEWS if v not in generated]
    if not todo:
        manifest.note(m, "plate emit views: every view is already generated; nothing requested")
        manifest.save(m)
        return []
    entry = budget.gate(m, VIEWS_BUDGET, estimate, model=model, items=todo)
    ins = request.inputs(m, [("source", front)], no_urls=no_urls, run=run)
    return [request.write_request(
        m, "plate", "views", view, model_type="image-to-image", render_type="I2I",
        prompt=SHEET_PROMPT(view), inputs=ins,
        target={"format": ["png"], "aspect": "3:4", "long_edge_px": 2048},
        must_satisfy=["the same design, colors, materials and proportions as the front plate (the source input)",
                      "the character %s" % VIEW_WORDS[view],
                      "the pose and background rules: %s" % POSE_AND_BACKGROUND],
        checked_at_ingest=CHECKED_AT_INGEST, budget_entry=entry,
        ingest=request.ingest_command(m, "plate", "views", view)) for view in todo]


# ---------------------------------------------------------------- ingest

def _record(m, step, item, result, att, *, prompt, render_type, input_media_ids, default_prompt,
            default_inputs, request_item, unrequested, supersede, stem, opener):
    """Resolve, check and record one result; returns the put_record outcome."""
    req_path = request.require_request(m, "plate", step, request_item, unrequested)
    req = json.loads(Path(req_path).read_text()) if req_path else {}

    def make(path, url, _kind):
        ids = [str(i) for i in input_media_ids] or [i["media_id"] for i in req.get("inputs") or []] \
            or list(default_inputs)
        return request.make_record(
            artifact=path, source_url=url, attestation=att,
            prompt=prompt if prompt is not None else (req.get("prompt") or default_prompt),
            render_type=render_type or req.get("render_type") or ("I2I" if ids else "T2I"),
            input_media_ids=ids, request_path=req_path, vendor_hint=m.get("vendor"))

    return request.record_result(m, "plate", item, result, make, stem=stem, ext=IMAGE_EXT,
                                 check=lambda path: request.check_kind(path, request.IMAGE_KINDS),
                                 bound_media_id=_media_ids(m).get(item), supersede=supersede, opener=opener)


def _front_bind_preconditions(m, asset_id, create):
    """Everything a front bind needs, checked before any governed write."""
    if create and m.get("asset_id"):
        raise ValueError("--create-asset: this manifest already has asset %s; bind further candidates "
                         "onto it without --create-asset" % m["asset_id"])
    if asset_id and m.get("asset_id") and str(asset_id) != str(m["asset_id"]):
        raise ValueError("--asset-id %s differs from the manifest's asset %s" % (asset_id, m["asset_id"]))
    if not (create or asset_id or m.get("asset_id")):
        raise ValueError("no asset_id: pass --asset-id or --create-asset")
    genvid_bind.require_assignee(m)
    if create:
        manifest.production_title(m)


def _views_bind_preconditions(m):
    if not m.get("asset_id"):
        raise ValueError("no asset_id on the manifest: the views bind onto the front plate's asset")
    genvid_bind.require_assignee(m)


def _bind_front(m, item, asset_id=None, create=False, fresh_asset=False, run=subprocess.run):
    # `fresh_asset=True` says the caller created `asset_id` moments ago in this same
    # call chain (a per-title static-prop chain does, under its own asset description),
    # so no image task can exist on it yet: it takes the same fire-and-forget claim
    # `create` takes. Never pass it for an asset that existed before the call.
    if create:
        asset_id = genvid_bind.create_asset(m["project_id"], m["name"], "cast_member",
                                            "%s character: %s" % (manifest.production_title(m), m["name"]),
                                            run=run)
    if asset_id:
        m["asset_id"] = asset_id
        manifest.save(m)
    asset_id = m["asset_id"]
    if create or fresh_asset:
        # No image task can exist on an asset created in this call chain, so the claim
        # is fire-and-forget for this bind. Nothing is cached: a later candidate's
        # ensure_claim reads the task, and waits on this payload until it has run.
        genvid_bind.claim_assignment(m, asset_id)
    else:
        # A pre-existing asset may have been approved since, which refuses this bind
        # until its task is reopened.
        genvid_bind.ensure_claim(m, asset_id, "plate.front")
    rec = _plate(m)["generated"][item]
    ids = _media_ids(m)
    ids[item] = genvid_bind.import_media(
        m["project_id"], link_type="cast_member_image", asset_id=asset_id, run=run,
        **request.bind_kwargs(rec, runner={"stage": "plate", "view": "front", "candidate": item,
                                           "size_px": rec.get("size_px")}))
    manifest.set_stage(m, "plate", media_ids=ids)
    manifest.save(m)
    return ids[item]


def _bind_view(m, view, run=subprocess.run):
    asset_id = m["asset_id"]
    # Every views bind gates: the front was bound or adopted in an earlier call, and
    # the reviewer may have approved the asset's image task since.
    genvid_bind.ensure_claim(m, asset_id, "plate.views")
    rec = _plate(m)["generated"][view]
    size = rec.get("size_px")
    runner = {"stage": "plate", "view": view, "size_px": size,
              "aspect": round(size[0] / size[1], 4) if size and size[1] else None}
    ids = _media_ids(m)
    ids[view] = genvid_bind.import_media(m["project_id"], link_type="cast_member_image", asset_id=asset_id,
                                         run=run, **request.bind_kwargs(rec, runner=runner))
    manifest.set_stage(m, "plate", media_ids=ids)
    manifest.save(m)
    return ids[view]


def ingest_front(m, item, result, att, *, asset_id=None, create=False, fresh_asset=False, prompt=None,
                 render_type=None, input_media_ids=(), record_only=False, supersede=False, unrequested=None,
                 opener=None, run=subprocess.run):
    """Record one front candidate and bind it; returns its media id (None with
    `record_only`). The first candidate on a new character passes `create`."""
    _check_candidate(item)
    if not record_only:
        _front_bind_preconditions(m, asset_id, create)
    outcome = _record(m, "front", item, result, att, prompt=prompt, render_type=render_type,
                      input_media_ids=input_media_ids, default_prompt=_plate(m).get("prompt"),
                      default_inputs=(), request_item=None, unrequested=unrequested, supersede=supersede,
                      stem="plate_%s" % item, opener=opener)
    if record_only:
        return None
    bound = _media_ids(m).get(item)
    if outcome == "unchanged" and bound:
        return bound
    return _bind_front(m, item, asset_id, create, fresh_asset, run=run)


def ingest_views(m, view, result, att, *, prompt=None, render_type=None, input_media_ids=(), record_only=False,
                 supersede=False, unrequested=None, opener=None, run=subprocess.run):
    """Record one view and bind it citing the front; returns its media id (None
    with `record_only`). The front must be bound or adopted."""
    _check_view(view)
    front = _media_ids(m).get("front")
    if not front:
        raise request.IngestError("no front plate: a view derives from the front, so run `plate select-front` "
                                  "before ingesting views")
    if not record_only:
        _views_bind_preconditions(m)
    outcome = _record(m, "views", view, result, att, prompt=prompt, render_type=render_type,
                      input_media_ids=input_media_ids, default_prompt=SHEET_PROMPT(view),
                      default_inputs=(front,), request_item=view, unrequested=unrequested,
                      supersede=supersede, stem="sheet_%s" % view, opener=opener)
    paths = dict(_plate(m).get("view_paths") or {})
    paths[view] = _plate(m)["generated"][view]["artifact"]
    manifest.set_stage(m, "plate", view_paths=paths)
    manifest.save(m)
    if record_only:
        return None
    bound = _media_ids(m).get(view)
    if outcome == "unchanged" and bound:
        return bound
    return _bind_view(m, view, run=run)


FRONT_EXT = {"png": "png", "jpeg": "jpg", "webp": "webp"}


def _fetch_adopted_front(m, media_id, run, opener):
    """Download an adopted front's own bytes from Genvid into the out dir and
    return the path. Mesh prep turns the model to face the way this image does
    before the rig, and refuses without it."""
    entry = genvid_bind.signed_urls(m["project_id"], [media_id], run=run)[0]
    part = Path(m["out_dir"]) / "plate_front.download"
    request.download(entry["signed_url"], part, opener=opener)
    try:
        kind = request.check_kind(part, request.IMAGE_KINDS)
    except request.IngestError:
        part.unlink(missing_ok=True)
        raise
    return str(part.replace(part.with_name("plate_front." + FRONT_EXT[kind])))


def select_front(m, media_id, asset_id=None, run=subprocess.run, opener=None):
    """Record which media row is the front plate.

    A bound candidate of this manifest becomes the front; the choice may change
    until a view is recorded, since every view derives from the front. Any other
    id is ADOPTED: a row already in Genvid (reviewed or drawn elsewhere) that is
    neither imported nor claimed here, since re-importing it would duplicate the
    row and attest provenance it does not have. Adopting needs the asset the row
    belongs to and never replaces a different recorded front. An adopted front's
    bytes are downloaded from Genvid and recorded as the front view path; running
    select-front again on an adopted front that has no path fetches it."""
    media_id = str(media_id or "").strip()
    if not media_id:
        raise ValueError("--media-id must be a non-empty media id")
    st = _plate(m)
    ids = _media_ids(m)
    current = ids.get("front")
    candidates = sorted(k for k, v in ids.items() if CANDIDATE_RE.match(k) and str(v) == media_id)
    if candidates:
        if current and current != media_id and any(v in (st.get("generated") or {}) or ids.get(v) for v in VIEWS):
            raise ValueError("the views were generated from front %s; refusing to make %s the front under them"
                             % (current, media_id))
        item = candidates[0]
        artifact = st["generated"][item]["artifact"]
        paths = dict(st.get("view_paths") or {}); paths["front"] = artifact
        ids["front"] = media_id
        entry = manifest.set_stage(m, "plate", media_ids=ids, media_id=media_id, artifact=artifact,
                                   view_paths=paths, front_candidate=item)
        entry.pop("front_adopted", None)
        if current and current != media_id:
            manifest.note(m, "plate select-front: front changed from %s to %s (%s)" % (current, media_id, item))
        manifest.save(m)
        return m
    aid = asset_id or m.get("asset_id")
    if not aid:
        raise ValueError("adopting media %s as the front needs the asset it belongs to: pass --asset-id" % media_id)
    if asset_id and m.get("asset_id") and str(asset_id) != str(m["asset_id"]):
        raise ValueError("--asset-id %s differs from the manifest's asset %s" % (asset_id, m["asset_id"]))
    genvid_bind.require_assignee(m)
    if current and current != media_id:
        raise ValueError("the manifest's front is already %s; refusing to replace it with %s" % (current, media_id))
    paths = dict(st.get("view_paths") or {})
    if current == media_id:
        if paths.get("front") and Path(paths["front"]).exists():
            return m
        paths["front"] = _fetch_adopted_front(m, media_id, run, opener)
        manifest.set_stage(m, "plate", view_paths=paths, artifact=paths["front"])
        manifest.note(m, "plate select-front: fetched adopted front %s from Genvid to %s" % (media_id, paths["front"]))
        manifest.save(m)
        return m
    paths["front"] = _fetch_adopted_front(m, media_id, run, opener)
    m["asset_id"] = aid
    ids["front"] = media_id
    manifest.set_stage(m, "plate", media_ids=ids, media_id=media_id, front_adopted=True,
                       view_paths=paths, artifact=paths["front"])
    manifest.note(m, "plate select-front: adopted existing media %s as the front plate; not re-imported; "
                     "its bytes fetched to %s" % (media_id, paths["front"]))
    manifest.save(m)
    return m


def bind(m, asset_id=None, create=False, fresh_asset=False, run=subprocess.run):
    """Bind every recorded plate item that has no media id yet, front candidates
    first; the re-run after a ClaimPending (or a --record-only ingest). Returns
    the media ids."""
    st = _plate(m)
    generated = st.get("generated") or {}
    ids = _media_ids(m)
    fronts = sorted((k for k in generated if CANDIDATE_RE.match(k) and not ids.get(k)),
                    key=lambda k: int(k[1:]))
    views_todo = [v for v in VIEWS if v in generated and not ids.get(v)]
    if not fronts and not views_todo:
        manifest.note(m, "plate bind: every recorded item is already bound")
        manifest.save(m)
        return ids
    if fronts:
        _front_bind_preconditions(m, asset_id, create)
    if views_todo:
        if not ids.get("front"):
            raise request.IngestError("views are recorded but no front is: run `plate select-front` first")
        if not fronts:
            _views_bind_preconditions(m)
    for i, item in enumerate(fronts):
        first = i == 0
        _bind_front(m, item, asset_id if first else None, create and first, fresh_asset and first, run=run)
    for view in views_todo:
        _bind_view(m, view, run=run)
    return _media_ids(m)


def views(m):
    return dict(m["stages"]["plate"]["view_paths"])

# The stated rule eval row E1 reads. check_plate_gaps.py measures the longest
# background run between the legs at seven heights (0.62-0.86 of the image) and
# prints it per row; nothing turned those numbers into a verdict, so E1 was
# structurally PEND on every run (witnessed 2026-09-04 on both bake-off legs).
# 8 px is the stated threshold. Measured against the July
# 50-stud character's plate on 2026-09-04 (its own plate.png in the game repo,
# check_plate_gaps.py rc=0): rows 0.62-0.86 read 5, 25, 2, 1, 2, 0, 6 px, so that
# APPROVED plate does not clear this rule at six of its seven rows. E1 is a
# non-gate row precisely because of that spread -- the number reports, the zoo
# verdict decides -- and the measurement is recorded here rather than left as an
# assumption about what a passing plate looks like.
GAP_MIN_PX = 8
GAPS_RULE = ("every row of the FRONT plate reports a leg gap >= %d px; a row that reports n/a "
             "fails it too (no measurable gap in the band is not a plate with legs apart); side "
             "and back views are exempt, since a strict profile has no leg gap to measure" % GAP_MIN_PX)

# `<path>  (1024x1536)` starts a per-image block; `  0.62    30px` / `  0.66  n/a`
# are its rows. Anything else -- the column header, the `compare` block's
# disagreement lines -- matches neither and is ignored.
_HEADER_RE = re.compile(r"^(?P<path>\S.*?)\s+\(\d+x\d+\)\s*$")
_ROW_RE = re.compile(r"^\s+(?P<frac>\d+\.\d+)\s+(?:(?P<px>\d+)px|n/a)\s*$")


def parse_gaps(stdout):
    """check_plate_gaps.py's report -> {path: [(row_fraction, gap_px or None), ...]}."""
    blocks, cur = {}, None
    for line in (stdout or "").splitlines():
        header = _HEADER_RE.match(line)
        if header:
            cur = header.group("path")
            blocks.setdefault(cur, [])
            continue
        row = _ROW_RE.match(line)
        if row is not None and cur is not None:
            px = row.group("px")
            blocks[cur].append((float(row.group("frac")), int(px) if px is not None else None))
    return blocks


def gaps_verdict(stdout, front_path):
    """(ok, rows, failures) for the front plate under GAPS_RULE.

    `ok` is None when the front plate produced no rows at all -- an honest "not
    measured", which E1 renders PEND. It is never True by default: a plate this
    function could not find in the report has not passed anything.
    """
    blocks = parse_gaps(stdout)
    rows = blocks.get(front_path)
    if rows is None and front_path:
        # The report echoes each path as it was passed on the command line; fall
        # back to the file name so a symlinked or relative invocation still lands.
        name = Path(front_path).name
        for path, r in blocks.items():
            if Path(path).name == name:
                rows = r
                break
    if not rows:
        return None, [], []
    failures = [[frac, px] for frac, px in rows if px is None or px < GAP_MIN_PX]
    return not failures, [[frac, px] for frac, px in rows], failures


def gaps(m):
    script = os.environ.get("PLATE_GAPS_PY")
    if not script:
        manifest.note(m, "plate gaps: PLATE_GAPS_PY unset; not measured"); manifest.save(m); return None
    py = str(Path(script).parent / ".venv" / "bin" / "python")
    r = subprocess.run([py, script] + list(views(m).values()), capture_output=True, text=True)
    # Record returncode and a stderr tail alongside stdout: check_plate_gaps.py prints its
    # report per-path as it goes, so a crash partway through leaves stdout looking like a
    # complete, healthy measurement unless the exit status is captured too. An empty stdout
    # from a wholesale failure must not read as "measured, nothing to flag" either -- both
    # are recorded, and a nonzero exit raises after the partial record is persisted.
    manifest.set_stage(m, "plate", gaps_stdout=r.stdout[-2000:], gaps_returncode=r.returncode,
                        gaps_stderr=r.stderr[-2000:])
    # A partial report from a crashed run cannot carry a verdict: the rule is over
    # EVERY row of the front plate, and a run that died mid-report may simply not
    # have printed the row that would have failed it. gaps_ok stays None there.
    if r.returncode == 0:
        ok, rows, failures = gaps_verdict(r.stdout, views(m).get("front"))
        manifest.set_stage(m, "plate", gaps_ok=ok, gaps_rows=rows, gaps_failures=failures,
                           gaps_rule=GAPS_RULE, gaps_min_px=GAP_MIN_PX)
        if ok is None:
            manifest.note(m, "plate gaps: no rows parsed for the front plate; gaps_ok not measured")
    else:
        manifest.set_stage(m, "plate", gaps_ok=None, gaps_rule=GAPS_RULE, gaps_min_px=GAP_MIN_PX)
    manifest.save(m)
    if r.returncode != 0:
        raise RuntimeError("check_plate_gaps.py exited %d: %s" % (r.returncode, r.stderr[-2000:] or "(no stderr)"))
    return r.stdout

def register(sub):
    p = sub.add_parser("plate"); s = p.add_subparsers(dest="cmd", required=True)
    e = s.add_parser("emit", help="write a generation request for the caller's own model")
    es = e.add_subparsers(dest="step", required=True)
    ef = es.add_parser("front", help="the front concept plate candidates")
    request.add_emit_args(ef, item_help="not used: one front request covers every candidate")
    ef.add_argument("--prompt", help="the front prompt (required unless stages.plate.prompt is recorded)")
    ef.add_argument("--input-media-id", action="append", default=[],
                    help="a Genvid media id to use as a reference image (repeatable); makes it image-to-image")
    ef.set_defaults(func=_emit_front)
    ev = es.add_parser("views", help="the back, left and right views, from the front")
    request.add_emit_args(ev, item_help="back, left or right; omit for every view not yet generated")
    ev.set_defaults(func=_emit_views)

    i = s.add_parser("ingest", help="record and bind a result the caller generated")
    ist = i.add_subparsers(dest="step", required=True)
    inf = ist.add_parser("front", help="one front candidate")
    request.add_ingest_args(inf, item_help="the candidate: c1, c2, ...")
    inf.add_argument("--asset-id", help="the character's existing asset")
    inf.add_argument("--create-asset", action="store_true", help="create the character's asset (first candidate)")
    inf.set_defaults(func=_ingest_front)
    inv = ist.add_parser("views", help="one view")
    request.add_ingest_args(inv, item_help="back, left or right")
    inv.set_defaults(func=_ingest_views)

    sf = s.add_parser("select-front", help="record which media row is the front plate (a bound candidate, or "
                                           "an existing row to adopt)")
    sf.add_argument("--manifest", required=True)
    sf.add_argument("--media-id", required=True)
    sf.add_argument("--asset-id", help="the asset an adopted row belongs to")
    sf.set_defaults(func=lambda x: _done(select_front(manifest.load(x.manifest), x.media_id, x.asset_id)))

    g = s.add_parser("gaps"); g.add_argument("--manifest", required=True); g.set_defaults(func=lambda x: gaps(manifest.load(x.manifest)))
    b = s.add_parser("bind", help="bind every recorded item not yet bound (the re-run)")
    b.add_argument("--manifest", required=True); b.add_argument("--asset-id")
    b.add_argument("--create-asset", action="store_true")
    b.set_defaults(func=lambda x: _done(bind(manifest.load(x.manifest), x.asset_id, x.create_asset)))


def _done(_result):
    """CLI commands return an exit code, never the value."""
    return None


def _emit_front(x):
    if x.item:
        raise SystemExit("plate emit front takes no --item: one request covers every candidate")
    print(emit_front(manifest.load(x.manifest), x.estimate, prompt=x.prompt, input_media_ids=x.input_media_id,
                     model=x.model, no_urls=x.no_urls))


def _emit_views(x):
    for path in emit_views(manifest.load(x.manifest), x.estimate, item=x.item, model=x.model, no_urls=x.no_urls):
        print(path)


def _ingest_kwargs(x):
    return dict(prompt=x.prompt, render_type=x.render_type, input_media_ids=x.input_media_id,
                record_only=x.record_only, supersede=x.supersede, unrequested=x.unrequested)


def _ingest_front(x):
    ingest_front(manifest.load(x.manifest), x.item, x.result, request.attestation_from_args(x),
                 asset_id=x.asset_id, create=x.create_asset, **_ingest_kwargs(x))


def _ingest_views(x):
    ingest_views(manifest.load(x.manifest), x.item, x.result, request.attestation_from_args(x), **_ingest_kwargs(x))
